ALL_US_STOCK_SYMBOLS = ["A", "AA", "AACB", "AACBR", "AACBU", "AACG", "AACT", "AAL", "AAM", "AAME", "AAMI", "AAOI",
                        "AAON",
                        "AAP", "AAPG", "AAPL", "AARD", "AAT", "AB", "ABAT", "ABBV", "ABCB", "ABCL", "ABEO", "ABEV",
                        "ABG",
                        "ABL", "ABLLL", "ABLLW", "ABLV", "ABM", "ABNB", "ABOS", "ABP", "ABPWW", "ABR", "ABSI", "ABT",
                        "ABTS", "ABUS", "ABVC", "ABVE", "ABVEW", "ABVX", "AC", "ACA", "ACAD", "ACB", "ACCO", "ACCS",
                        "ACDC", "ACEL", "ACET", "ACGL", "ACGLN", "ACGLO", "ACHC", "ACHR", "ACHV", "ACI", "ACIC", "ACIU",
                        "ACIW", "ACLS", "ACLX", "ACM", "ACMR", "ACN", "ACNB", "ACNT", "ACOG", "ACON", "ACONW", "ACP",
                        "ACR", "ACRE", "ACRS", "ACRV", "ACT", "ACTG", "ACTU", "ACU", "ACV", "ACVA", "ACXP", "ADAG",
                        "ADAP",
                        "ADBE", "ADC", "ADCT", "ADD", "ADEA", "ADGM", "ADI", "ADIL", "ADM", "ADMA", "ADN", "ADNT",
                        "ADNWW",
                        "ADP", "ADPT", "ADSE", "ADSEW", "ADSK", "ADT", "ADTN", "ADTX", "ADUR", "ADUS", "ADV", "ADVB",
                        "ADVM", "ADVWW", "ADX", "ADXN", "AEE", "AEF", "AEFC", "AEG", "AEHL", "AEHR", "AEI", "AEIS",
                        "AEM",
                        "AEMD", "AENT", "AENTW", "AEO", "AEON", "AEP", "AER", "AERT", "AERTW", "AES", "AESI", "AEVA",
                        "AEVAW", "AEYE", "AFB", "AFBI", "AFCG", "AFG", "AFGB", "AFGC", "AFGD", "AFGE", "AFJKR", "AFL",
                        "AFMD", "AFRI", "AFRIW", "AFRM", "AFYA", "AG", "AGAE", "AGCO", "AGD", "AGEN", "AGFY", "AGH",
                        "AGI",
                        "AGIO", "AGL", "AGM", "AGMH", "AGNC", "AGNCL", "AGNCM", "AGNCN", "AGNCO", "AGNCP", "AGO",
                        "AGRI",
                        "AGRO", "AGS", "AGX", "AGYS", "AHCO", "AHG", "AHH", "AHL", "AHR", "AHT", "AI", "AIFE", "AIFF",
                        "AIFU", "AIG", "AIHS", "AIMAU", "AIMAW", "AIMBU", "AIMD", "AIMDW", "AIN", "AIO", "AIOT", "AIP",
                        "AIR", "AIRE", "AIRG", "AIRI", "AIRJ", "AIRJW", "AIRS", "AIRT", "AIRTP", "AISP", "AISPW", "AIT",
                        "AIV", "AIXI", "AIZ", "AIZN", "AJG", "AKA", "AKAM", "AKAN", "AKBA", "AKO", "AKR", "AKRO",
                        "AKTX",
                        "AKYA", "AL", "ALAB", "ALAR", "ALB", "ALBT", "ALC", "ALCO", "ALCY", "ALCYW", "ALDF", "ALDFU",
                        "ALDFW", "ALDX", "ALE", "ALEC", "ALEX", "ALF", "ALFUU", "ALFUW", "ALG", "ALGM", "ALGN", "ALGS",
                        "ALGT", "ALHC", "ALIT", "ALK", "ALKS", "ALKT", "ALL", "ALLE", "ALLK", "ALLO", "ALLR", "ALLT",
                        "ALLY", "ALMS", "ALMU", "ALNT", "ALNY", "ALOT", "ALRM", "ALRS", "ALSN", "ALT", "ALTG", "ALTI",
                        "ALTO", "ALTS", "ALUR", "ALV", "ALVO", "ALVOW", "ALX", "ALXO", "ALZN", "AM", "AMAL", "AMAT",
                        "AMBA", "AMBC", "AMBI", "AMBO", "AMBP", "AMBR", "AMC", "AMCR", "AMCX", "AMD", "AME", "AMED",
                        "AMG",
                        "AMGN", "AMH", "AMIX", "AMKR", "AMLX", "AMN", "AMOD", "AMODW", "AMP", "AMPG", "AMPGW", "AMPH",
                        "AMPL", "AMPX", "AMPY", "AMR", "AMRC", "AMRK", "AMRN", "AMRX", "AMS", "AMSC", "AMSF", "AMST",
                        "AMT", "AMTB", "AMTD", "AMTM", "AMTX", "AMWD", "AMWL", "AMX", "AMZE", "AMZN", "AN", "ANAB",
                        "ANDE",
                        "ANEB", "ANET", "ANF", "ANG", "ANGH", "ANGHW", "ANGI", "ANGO", "ANIK", "ANIP", "ANIX", "ANL",
                        "ANNA", "ANNAW", "ANNX", "ANRO", "ANSC", "ANSCW", "ANSS", "ANTE", "ANTX", "ANVS", "ANY", "AOD",
                        "AOMN", "AOMR", "AON", "AORT", "AOS", "AOSL", "AOUT", "AP", "APA", "APAM", "APCX", "APD",
                        "APDN",
                        "APEI", "APG", "APGE", "APH", "API", "APLD", "APLE", "APLM", "APLS", "APLT", "APM", "APO",
                        "APOG",
                        "APOS", "APP", "APPF", "APPN", "APPS", "APRE", "APT", "APTV", "APVO", "APWC", "APYX", "AQB",
                        "AQMS", "AQN", "AQNB", "AQST", "AR", "ARAY", "ARBB", "ARBE", "ARBEW", "ARBK", "ARBKL", "ARCB",
                        "ARCC", "ARCO", "ARCT", "ARDC", "ARDT", "ARDX", "ARE", "AREB", "AREBW", "AREC", "AREN", "ARES",
                        "ARGD", "ARGO", "ARGX", "ARHS", "ARI", "ARIS", "ARKO", "ARKOW", "ARKR", "ARL", "ARLO", "ARLP",
                        "ARM", "ARMK", "ARMN", "ARMP", "AROC", "AROW", "ARQ", "ARQQ", "ARQQW", "ARQT", "ARR", "ARRY",
                        "ARTL", "ARTNA", "ARTV", "ARTW", "ARVN", "ARW", "ARWR", "AS", "ASA", "ASAN", "ASB", "ASBA",
                        "ASBP",
                        "ASBPW", "ASC", "ASG", "ASGI", "ASGN", "ASH", "ASIX", "ASLE", "ASM", "ASMB", "ASML", "ASND",
                        "ASNS", "ASO", "ASPC", "ASPI", "ASPN", "ASPS", "ASR", "ASRT", "ASRV", "ASST", "ASTC", "ASTE",
                        "ASTH", "ASTI", "ASTL", "ASTLW", "ASTS", "ASUR", "ASX", "ASYS", "ATAI", "ATAT", "ATCH", "ATCO",
                        "ATCOL", "ATEC", "ATEN", "ATER", "ATEX", "ATGE", "ATGL", "ATH", "ATHA", "ATHE", "ATHM", "ATHR",
                        "ATHS", "ATI", "ATII", "ATIIU", "ATIIW", "ATKR", "ATLC", "ATLCL", "ATLCP", "ATLCZ", "ATLN",
                        "ATLO",
                        "ATLX", "ATMC", "ATMU", "ATMVR", "ATNF", "ATNFW", "ATNI", "ATNM", "ATO", "ATOM", "ATOS", "ATPC",
                        "ATR", "ATRA", "ATRC", "ATRO", "ATS", "ATUS", "ATXG", "ATXS", "ATYR", "AU", "AUB", "AUBN",
                        "AUDC",
                        "AUID", "AUNA", "AUPH", "AUR", "AURA", "AUROW", "AUST", "AUTL", "AUUD", "AUUDW", "AVA", "AVAH",
                        "AVAL", "AVAV", "AVB", "AVBP", "AVD", "AVDL", "AVDX", "AVGO", "AVIR", "AVK", "AVNS", "AVNT",
                        "AVNW", "AVO", "AVPT", "AVPTW", "AVR", "AVT", "AVTE", "AVTR", "AVTX", "AVXL", "AVY", "AWF",
                        "AWI",
                        "AWK", "AWP", "AWR", "AWRE", "AWX", "AX", "AXDX", "AXGN", "AXIL", "AXL", "AXON", "AXP", "AXR",
                        "AXS", "AXSM", "AXTA", "AXTI", "AYI", "AYRO", "AYTU", "AZ", "AZEK", "AZI", "AZN", "AZO", "AZTA",
                        "AZTR", "AZUL", "AZZ", "B", "BA", "BABA", "BAC", "BACQ", "BACQU", "BAER", "BAERW", "BAFN",
                        "BAH",
                        "BAK", "BALL", "BALY", "BAM", "BANC", "BAND", "BANF", "BANFP", "BANL", "BANR", "BANX", "BAOS",
                        "BAP", "BARK", "BASE", "BATL", "BATRA", "BATRK", "BAX", "BAYA", "BAYAR", "BB", "BBAI", "BBAR",
                        "BBCP", "BBD", "BBDC", "BBDO", "BBGI", "BBIO", "BBLG", "BBLGW", "BBN", "BBNX", "BBSI", "BBU",
                        "BBUC", "BBVA", "BBW", "BBWI", "BBY", "BC", "BCAB", "BCAL", "BCAT", "BCAX", "BCBP", "BCC",
                        "BCDA",
                        "BCE", "BCG", "BCH", "BCLI", "BCML", "BCO", "BCPC", "BCRX", "BCS", "BCSF", "BCTX", "BCTXW",
                        "BCV",
                        "BCX", "BCYC", "BDC", "BDJ", "BDL", "BDMD", "BDN", "BDRX", "BDSX", "BDTX", "BDX", "BE", "BEAG",
                        "BEAGR", "BEAGU", "BEAM", "BEAT", "BEATW", "BECN", "BEDU", "BEEM", "BEEP", "BEKE", "BELFA",
                        "BELFB", "BEN", "BENF", "BENFW", "BEP", "BEPC", "BEPH", "BEPI", "BEPJ", "BERY", "BETR", "BF",
                        "BFAM", "BFC", "BFH", "BFIN", "BFK", "BFLY", "BFRG", "BFRGW", "BFRI", "BFRIW", "BFS", "BFST",
                        "BFZ", "BG", "BGB", "BGC", "BGFV", "BGH", "BGI", "BGLC", "BGM", "BGR", "BGS", "BGSF", "BGT",
                        "BGX",
                        "BGY", "BH", "BHAT", "BHB", "BHC", "BHE", "BHF", "BHFAL", "BHFAM", "BHFAN", "BHFAO", "BHFAP",
                        "BHK", "BHLB", "BHM", "BHP", "BHR", "BHRB", "BHST", "BHV", "BHVN", "BIAF", "BIDU", "BIGC",
                        "BIIB",
                        "BILI", "BILL", "BIO", "BIOA", "BIOX", "BIP", "BIPC", "BIPH", "BIPI", "BIPJ", "BIRD", "BIRK",
                        "BIT", "BITF", "BIVI", "BIYA", "BJ", "BJDX", "BJRI", "BK", "BKD", "BKE", "BKH", "BKHA", "BKHAR",
                        "BKKT", "BKN", "BKNG", "BKR", "BKSY", "BKT", "BKTI", "BKU", "BKV", "BKYI", "BL", "BLBD", "BLBX",
                        "BLCO", "BLD", "BLDE", "BLDEW", "BLDP", "BLDR", "BLE", "BLFS", "BLFY", "BLIN", "BLIV", "BLK",
                        "BLKB", "BLMN", "BLMZ", "BLND", "BLNE", "BLNK", "BLRX", "BLTE", "BLUE", "BLW", "BLX", "BLZE",
                        "BMA", "BMBL", "BME", "BMEA", "BMEZ", "BMGL", "BMI", "BML", "BMN", "BMO", "BMR", "BMRA", "BMRC",
                        "BMRN", "BMY", "BN", "BNAI", "BNAIW", "BNED", "BNGO", "BNH", "BNJ", "BNL", "BNR", "BNRG", "BNS",
                        "BNT", "BNTC", "BNTX", "BNY", "BNZI", "BNZIW", "BOC", "BODI", "BOE", "BOF", "BOH", "BOKF",
                        "BOLD",
                        "BOLT", "BON", "BOOM", "BOOT", "BORR", "BOSC", "BOTJ", "BOW", "BOWN", "BOWNR", "BOWNU", "BOX",
                        "BOXL", "BP", "BPMC", "BPOP", "BPOPM", "BPRN", "BPT", "BPYPM", "BPYPN", "BPYPO", "BPYPP", "BQ",
                        "BR", "BRAG", "BRBR", "BRBS", "BRC", "BRCC", "BRDG", "BREA", "BRFH", "BRFS", "BRIA", "BRID",
                        "BRK",
                        "BRKL", "BRKR", "BRLS", "BRLSW", "BRLT", "BRN", "BRNS", "BRO", "BROG", "BROS", "BRSP", "BRT",
                        "BRTX", "BRW", "BRX", "BRY", "BRZE", "BSAC", "BSBK", "BSBR", "BSET", "BSGM", "BSII", "BSIIW",
                        "BSL", "BSLK", "BSM", "BSRR", "BST", "BSTZ", "BSVN", "BSX", "BSY", "BTA", "BTAI", "BTBD",
                        "BTBT",
                        "BTCM", "BTCS", "BTCT", "BTDR", "BTE", "BTG", "BTI", "BTM", "BTMD", "BTMWW", "BTO", "BTOC",
                        "BTOG",
                        "BTSG", "BTSGU", "BTT", "BTU", "BTX", "BTZ", "BUD", "BUI", "BUJA", "BUJAR", "BUJAU", "BUJAW",
                        "BULL", "BULLW", "BULLZ", "BUR", "BURL", "BURU", "BUSE", "BV", "BVFL", "BVN", "BVS", "BW",
                        "BWA",
                        "BWAY", "BWB", "BWBBP", "BWEN", "BWFG", "BWG", "BWIN", "BWLP", "BWMN", "BWMX", "BWNB", "BWSN",
                        "BWXT", "BX", "BXC", "BXMT", "BXMX", "BXP", "BXSL", "BY", "BYD", "BYFC", "BYM", "BYND", "BYON",
                        "BYRN", "BYSI", "BZ", "BZAI", "BZAIW", "BZFD", "BZFDW", "BZH", "BZUN", "C", "CAAP", "CAAS",
                        "CABA",
                        "CABO", "CAC", "CACC", "CACI", "CADE", "CADL", "CAE", "CAF", "CAG", "CAH", "CAKE", "CAL",
                        "CALC",
                        "CALM", "CALX", "CAMP", "CAMT", "CAN", "CANF", "CANG", "CAPL", "CAPN", "CAPR", "CAPS", "CAPT",
                        "CAR", "CARE", "CARG", "CARM", "CARR", "CARS", "CART", "CARV", "CASH", "CASI", "CASK", "CASS",
                        "CASY", "CAT", "CATO", "CATX", "CATY", "CAVA", "CB", "CBAN", "CBAT", "CBFV", "CBL", "CBLL",
                        "CBNA",
                        "CBNK", "CBRE", "CBRL", "CBSH", "CBT", "CBU", "CBUS", "CBZ", "CC", "CCAP", "CCB", "CCBG",
                        "CCCC",
                        "CCCS", "CCD", "CCEC", "CCEL", "CCEP", "CCG", "CCGWW", "CCI", "CCIA", "CCIF", "CCIR", "CCIRU",
                        "CCIRW", "CCIX", "CCIXU", "CCIXW", "CCJ", "CCK", "CCL", "CCLD", "CCLDO", "CCM", "CCNE", "CCNEP",
                        "CCO", "CCOI", "CCRD", "CCRN", "CCS", "CCSI", "CCTG", "CCU", "CCZ", "CDE", "CDIO", "CDIOW",
                        "CDLR",
                        "CDLX", "CDNA", "CDNS", "CDP", "CDR", "CDRE", "CDRO", "CDROW", "CDT", "CDTG", "CDTTW", "CDTX",
                        "CDW", "CDXS", "CDZI", "CDZIP", "CE", "CEAD", "CEADW", "CECO", "CEE", "CEG", "CELC", "CELH",
                        "CELU", "CELUW", "CELZ", "CENN", "CENT", "CENTA", "CENX", "CEP", "CEPO", "CEPU", "CERO",
                        "CEROW",
                        "CERS", "CERT", "CET", "CETX", "CETY", "CEV", "CEVA", "CF", "CFBK", "CFFI", "CFFN", "CFG",
                        "CFLT",
                        "CFR", "CFSB", "CG", "CGABL", "CGAU", "CGBD", "CGBDL", "CGBS", "CGBSW", "CGC", "CGEM", "CGEN",
                        "CGNT", "CGNX", "CGO", "CGON", "CGTL", "CGTX", "CHA", "CHAR", "CHARR", "CHCI", "CHCO", "CHCT",
                        "CHD", "CHDN", "CHE", "CHEB", "CHEF", "CHEK", "CHGG", "CHH", "CHI", "CHKP", "CHMG", "CHMI",
                        "CHN",
                        "CHNR", "CHPT", "CHR", "CHRD", "CHRO", "CHRS", "CHRW", "CHSCL", "CHSCM", "CHSCN", "CHSCO",
                        "CHSCP",
                        "CHSN", "CHT", "CHTR", "CHW", "CHWY", "CHX", "CHY", "CI", "CIA", "CIB", "CICB", "CIEN", "CIF",
                        "CIFR", "CIFRW", "CIG", "CIGI", "CIGL", "CII", "CIIT", "CIK", "CIM", "CIMN", "CIMO", "CINF",
                        "CING", "CINGW", "CINT", "CIO", "CION", "CISO", "CISS", "CIVB", "CIVI", "CIX", "CJET", "CJMB",
                        "CKPT", "CKX", "CL", "CLAR", "CLB", "CLBK", "CLBR", "CLBT", "CLCO", "CLDI", "CLDT", "CLDX",
                        "CLEU",
                        "CLF", "CLFD", "CLGN", "CLH", "CLIK", "CLIR", "CLLS", "CLM", "CLMB", "CLMT", "CLNE", "CLNN",
                        "CLNNW", "CLOV", "CLPR", "CLPS", "CLPT", "CLRB", "CLRO", "CLS", "CLSD", "CLSK", "CLSKW", "CLST",
                        "CLVT", "CLW", "CLWT", "CLX", "CLYM", "CM", "CMA", "CMBM", "CMBT", "CMC", "CMCL", "CMCM",
                        "CMCO",
                        "CMCSA", "CMCT", "CME", "CMG", "CMI", "CMLS", "CMMB", "CMND", "CMP", "CMPO", "CMPOW", "CMPR",
                        "CMPS", "CMPX", "CMRE", "CMS", "CMSA", "CMSC", "CMSD", "CMT", "CMTG", "CMTL", "CMU", "CNA",
                        "CNC",
                        "CNCK", "CNCKW", "CNDT", "CNET", "CNEY", "CNF", "CNFR", "CNFRZ", "CNH", "CNI", "CNK", "CNL",
                        "CNM",
                        "CNMD", "CNNE", "CNO", "CNOB", "CNOBP", "CNP", "CNQ", "CNR", "CNS", "CNSP", "CNTA", "CNTB",
                        "CNTM",
                        "CNTX", "CNTY", "CNVS", "CNX", "CNXC", "CNXN", "COCH", "COCHW", "COCO", "COCP", "CODA", "CODI",
                        "CODX", "COE", "COEP", "COEPW", "COF", "COFS", "COGT", "COHN", "COHR", "COHU", "COIN", "COKE",
                        "COLA", "COLAU", "COLB", "COLD", "COLL", "COLM", "COMM", "COMP", "CON", "COO", "COOK", "COOP",
                        "COOT", "COP", "COR", "CORT", "CORZ", "CORZW", "CORZZ", "COSM", "COST", "COTY", "COUR", "COYA",
                        "CP", "CPA", "CPAC", "CPAY", "CPB", "CPBI", "CPF", "CPHC", "CPHI", "CPIX", "CPK", "CPNG",
                        "CPOP",
                        "CPRI", "CPRT", "CPRX", "CPS", "CPSH", "CPSS", "CPT", "CPZ", "CQP", "CR", "CRAI", "CRBD",
                        "CRBG",
                        "CRBP", "CRBU", "CRC", "CRCT", "CRD", "CRDF", "CRDL", "CRDO", "CREG", "CRESW", "CRESY", "CREV",
                        "CREVW", "CREX", "CRF", "CRGO", "CRGOW", "CRGX", "CRGY", "CRH", "CRI", "CRIS", "CRK", "CRL",
                        "CRM",
                        "CRMD", "CRML", "CRMLW", "CRMT", "CRNC", "CRNT", "CRNX", "CRON", "CROX", "CRS", "CRSP", "CRSR",
                        "CRT", "CRTO", "CRUS", "CRVL", "CRVO", "CRVS", "CRWD", "CRWS", "CRWV", "CSAI", "CSAN", "CSBR",
                        "CSCI", "CSCO", "CSGP", "CSGS", "CSIQ", "CSL", "CSPI", "CSQ", "CSR", "CSTE", "CSTL", "CSTM",
                        "CSV",
                        "CSWC", "CSWCZ", "CSWI", "CSX", "CTA", "CTAS", "CTBB", "CTBI", "CTDD", "CTEV", "CTGO", "CTKB",
                        "CTLP", "CTM", "CTMX", "CTNM", "CTNT", "CTO", "CTOR", "CTOS", "CTRA", "CTRE", "CTRI", "CTRM",
                        "CTRN", "CTS", "CTSH", "CTSO", "CTVA", "CTXR", "CUB", "CUBA", "CUBB", "CUBE", "CUBI", "CUBWU",
                        "CUBWW", "CUE", "CUK", "CULP", "CUPR", "CURB", "CURI", "CURIW", "CURR", "CURV", "CUZ", "CVAC",
                        "CVBF", "CVCO", "CVE", "CVEO", "CVGI", "CVGW", "CVI", "CVKD", "CVLG", "CVLT", "CVM", "CVNA",
                        "CVR",
                        "CVRX", "CVS", "CVU", "CVV", "CVX", "CW", "CWAN", "CWBC", "CWCO", "CWD", "CWEN", "CWH", "CWK",
                        "CWST", "CWT", "CX", "CXAI", "CXAIW", "CXDO", "CXE", "CXH", "CXM", "CXT", "CXW", "CYBN", "CYBR",
                        "CYCC", "CYCCP", "CYCN", "CYCU", "CYCUW", "CYD", "CYH", "CYN", "CYRX", "CYTK", "CZFS", "CZNC",
                        "CZR", "CZWI", "D", "DAC", "DADA", "DAIO", "DAKT", "DAL", "DALN", "DAN", "DAO", "DAR", "DARE",
                        "DASH", "DATS", "DATSW", "DAVA", "DAVE", "DAVEW", "DAWN", "DAY", "DB", "DBD", "DBI", "DBL",
                        "DBRG",
                        "DBVT", "DBX", "DC", "DCBO", "DCGO", "DCI", "DCO", "DCOM", "DCOMG", "DCOMP", "DCTH", "DD",
                        "DDC",
                        "DDD", "DDI", "DDL", "DDOG", "DDS", "DDT", "DE", "DEA", "DEC", "DECK", "DEI", "DELL", "DENN",
                        "DEO", "DERM", "DESP", "DEVS", "DFH", "DFIN", "DFLI", "DFLIW", "DFP", "DFS", "DG", "DGICA",
                        "DGICB", "DGII", "DGLY", "DGNX", "DGX", "DGXX", "DH", "DHAI", "DHAIW", "DHC", "DHCNI", "DHCNL",
                        "DHF", "DHI", "DHIL", "DHR", "DHT", "DHX", "DHY", "DIAX", "DIBS", "DIN", "DINO", "DIOD", "DIS",
                        "DIST", "DISTR", "DISTW", "DIT", "DJCO", "DJT", "DJTWW", "DK", "DKL", "DKNG", "DKS", "DLB",
                        "DLHC",
                        "DLNG", "DLO", "DLPN", "DLR", "DLTH", "DLTR", "DLX", "DLY", "DMA", "DMAA", "DMAAR", "DMAAU",
                        "DMAC", "DMB", "DMF", "DMLP", "DMN", "DMO", "DMRC", "DMYY", "DNA", "DNB", "DNLI", "DNN", "DNOW",
                        "DNP", "DNTH", "DNUT", "DOC", "DOCN", "DOCS", "DOCU", "DOGZ", "DOLE", "DOMH", "DOMO", "DOOO",
                        "DORM", "DOUG", "DOV", "DOW", "DOX", "DOYU", "DPG", "DPRO", "DPZ", "DQ", "DRCT", "DRD", "DRDB",
                        "DRDBU", "DRH", "DRI", "DRIO", "DRMA", "DRMAW", "DRRX", "DRS", "DRTS", "DRUG", "DRVN", "DSGN",
                        "DSGR", "DSGX", "DSL", "DSM", "DSP", "DSS", "DSU", "DSWL", "DSX", "DSY", "DSYWW", "DT", "DTB",
                        "DTCK", "DTE", "DTF", "DTG", "DTI", "DTIL", "DTM", "DTSQ", "DTSS", "DTST", "DTW", "DUK", "DUKB",
                        "DUO", "DUOL", "DUOT", "DV", "DVA", "DVAX", "DVLT", "DVN", "DVS", "DWSN", "DWTX", "DX", "DXC",
                        "DXCM", "DXF", "DXLG", "DXPE", "DXR", "DXST", "DXYZ", "DY", "DYAI", "DYCQ", "DYN", "DYNX",
                        "DYNXU",
                        "DYNXW", "E", "EA", "EAD", "EAF", "EAI", "EARN", "EAT", "EB", "EBAY", "EBC", "EBF", "EBMT",
                        "EBON",
                        "EBR", "EBS", "EBTC", "EC", "ECAT", "ECBK", "ECC", "ECCC", "ECCF", "ECCU", "ECCV", "ECCW",
                        "ECCX",
                        "ECDA", "ECDAW", "ECF", "ECG", "ECL", "ECO", "ECOR", "ECPG", "ECVT", "ECX", "ECXWW", "ED",
                        "EDAP",
                        "EDBL", "EDBLW", "EDD", "EDF", "EDHL", "EDIT", "EDN", "EDRY", "EDSA", "EDTK", "EDU", "EDUC",
                        "EE",
                        "EEA", "EEFT", "EEIQ", "EEX", "EFC", "EFOI", "EFR", "EFSC", "EFSCP", "EFSI", "EFT", "EFX",
                        "EFXT",
                        "EG", "EGAN", "EGBN", "EGHT", "EGO", "EGP", "EGY", "EH", "EHAB", "EHC", "EHGO", "EHI", "EHLD",
                        "EHTH", "EIC", "EICA", "EICB", "EICC", "EIG", "EIIA", "EIM", "EIX", "EJH", "EKSO", "EL", "ELA",
                        "ELAB", "ELAN", "ELBM", "ELC", "ELDN", "ELEV", "ELF", "ELLO", "ELMD", "ELME", "ELP", "ELPC",
                        "ELPW", "ELS", "ELSE", "ELTK", "ELTX", "ELUT", "ELV", "ELVA", "ELVN", "ELWS", "EM", "EMBC",
                        "EMCG",
                        "EMCGR", "EMD", "EME", "EMF", "EML", "EMN", "EMO", "EMP", "EMR", "EMX", "ENB", "ENFY", "ENGN",
                        "ENGNW", "ENGS", "ENIC", "ENJ", "ENLT", "ENLV", "ENO", "ENOV", "ENPH", "ENR", "ENS", "ENSC",
                        "ENSG", "ENTA", "ENTG", "ENTO", "ENTX", "ENVA", "ENVB", "ENVX", "ENX", "EOD", "EOG", "EOI",
                        "EOLS",
                        "EONR", "EOS", "EOSE", "EOSEW", "EOT", "EP", "EPAC", "EPAM", "EPC", "EPD", "EPIX", "EPM",
                        "EPOW",
                        "EPR", "EPRT", "EPRX", "EPSM", "EPSN", "EPWK", "EQ", "EQBK", "EQH", "EQIX", "EQNR", "EQR",
                        "EQS",
                        "EQT", "EQV", "EQX", "ERAS", "ERC", "ERH", "ERIC", "ERIE", "ERII", "ERJ", "ERNA", "ERO", "ES",
                        "ESAB", "ESCA", "ESE", "ESEA", "ESGL", "ESGR", "ESGRO", "ESGRP", "ESHA", "ESI", "ESLA", "ESLT",
                        "ESNT", "ESOA", "ESP", "ESPR", "ESQ", "ESRT", "ESS", "ESSA", "ESTA", "ESTC", "ET", "ETB", "ETD",
                        "ETG", "ETI", "ETJ", "ETN", "ETNB", "ETO", "ETON", "ETR", "ETSY", "ETV", "ETW", "ETWO", "ETX",
                        "ETY", "EU", "EUDA", "EUDAW", "EURK", "EURKU", "EVAX", "EVBN", "EVC", "EVCM", "EVER", "EVEX",
                        "EVF", "EVG", "EVGN", "EVGO", "EVGOW", "EVH", "EVI", "EVLV", "EVLVW", "EVM", "EVN", "EVO",
                        "EVOK",
                        "EVR", "EVRG", "EVRI", "EVT", "EVTC", "EVTL", "EVTV", "EVV", "EW", "EWBC", "EWCZ", "EWTX",
                        "EXAS",
                        "EXC", "EXE", "EXEEL", "EXEL", "EXFY", "EXG", "EXK", "EXLS", "EXOD", "EXOZ", "EXP", "EXPD",
                        "EXPE",
                        "EXPI", "EXPO", "EXR", "EXTR", "EYE", "EYEN", "EYPT", "EZGO", "EZPW", "F", "FA", "FAAS",
                        "FAASW",
                        "FACT", "FAF", "FAMI", "FANG", "FARM", "FARO", "FAST", "FAT", "FATBB", "FATBP", "FATBW", "FATE",
                        "FATN", "FAX", "FBGL", "FBIN", "FBIO", "FBIOP", "FBIZ", "FBK", "FBLA", "FBLG", "FBNC", "FBP",
                        "FBRT", "FBRX", "FBYD", "FBYDW", "FC", "FCAP", "FCBC", "FCCO", "FCEL", "FCF", "FCFS", "FCN",
                        "FCNCA", "FCNCO", "FCNCP", "FCO", "FCPT", "FCRX", "FCT", "FCUV", "FCX", "FDBC", "FDMT", "FDP",
                        "FDSB", "FDUS", "FDX", "FE", "FEAM", "FEBO", "FEDU", "FEIM", "FELE", "FEMY", "FENC", "FENG",
                        "FER",
                        "FERA", "FERAR", "FERAU", "FERG", "FET", "FF", "FFA", "FFAI", "FFAIW", "FFBC", "FFC", "FFIC",
                        "FFIN", "FFIV", "FFWM", "FG", "FGB", "FGBI", "FGBIP", "FGEN", "FGF", "FGI", "FGIWW", "FGL",
                        "FGMC",
                        "FGMCR", "FGMCU", "FGN", "FGSN", "FHB", "FHI", "FHN", "FHTX", "FI", "FIBK", "FICO", "FIGS",
                        "FIHL",
                        "FINS", "FINV", "FINW", "FIP", "FIS", "FISI", "FITB", "FITBI", "FITBO", "FITBP", "FIVE", "FIVN",
                        "FIX", "FIZZ", "FKWL", "FL", "FLC", "FLD", "FLDDW", "FLEX", "FLG", "FLGC", "FLGT", "FLIC",
                        "FLL",
                        "FLNC", "FLNG", "FLNT", "FLO", "FLOC", "FLR", "FLS", "FLUT", "FLUX", "FLWS", "FLX", "FLXS",
                        "FLYE",
                        "FLYW", "FLYX", "FMAO", "FMBH", "FMC", "FMN", "FMNB", "FMS", "FMST", "FMTO", "FMX", "FMY", "FN",
                        "FNB", "FND", "FNF", "FNGR", "FNKO", "FNLC", "FNV", "FNWB", "FNWD", "FOA", "FOF", "FOLD",
                        "FONR",
                        "FOR", "FORA", "FORD", "FORL", "FORM", "FORR", "FORTY", "FOSL", "FOSLL", "FOUR", "FOX", "FOXA",
                        "FOXF", "FOXX", "FPAY", "FPF", "FPH", "FPI", "FR", "FRA", "FRAF", "FRBA", "FRD", "FRGE", "FRGT",
                        "FRHC", "FRME", "FRMEP", "FRO", "FROG", "FRPH", "FRPT", "FRSH", "FRST", "FRSX", "FRT", "FSBC",
                        "FSBW", "FSCO", "FSEA", "FSFG", "FSHPR", "FSHPU", "FSI", "FSK", "FSLR", "FSLY", "FSM", "FSP",
                        "FSS", "FSTR", "FSUN", "FSV", "FT", "FTAI", "FTAIM", "FTAIN", "FTCI", "FTDR", "FTEK", "FTEL",
                        "FTF", "FTFT", "FTHM", "FTHY", "FTI", "FTK", "FTLF", "FTNT", "FTRE", "FTS", "FTV", "FUBO",
                        "FUFU",
                        "FUFUW", "FUL", "FULC", "FULT", "FULTP", "FUN", "FUNC", "FUND", "FURY", "FUSB", "FUTU", "FVCB",
                        "FVN", "FVNNR", "FVR", "FVRR", "FWONA", "FWONK", "FWRD", "FWRG", "FXNC", "FYBR", "G", "GAB",
                        "GABC", "GAIA", "GAIN", "GAINI", "GAINL", "GAINN", "GAINZ", "GALT", "GAM", "GAMB", "GAME",
                        "GAN",
                        "GANX", "GAP", "GASS", "GATX", "GAU", "GAUZ", "GB", "GBAB", "GBCI", "GBDC", "GBIO", "GBLI",
                        "GBR",
                        "GBTG", "GBX", "GCBC", "GCI", "GCL", "GCLWW", "GCMG", "GCMGW", "GCO", "GCT", "GCTK", "GCTS",
                        "GCV",
                        "GD", "GDC", "GDDY", "GDEN", "GDEV", "GDHG", "GDL", "GDO", "GDOT", "GDRX", "GDS", "GDTC", "GDV",
                        "GDYN", "GE", "GECC", "GECCH", "GECCI", "GECCO", "GECCZ", "GEF", "GEG", "GEGGL", "GEHC", "GEL",
                        "GELS", "GEN", "GENC", "GENI", "GENK", "GENVR", "GEO", "GEOS", "GERN", "GES", "GETY", "GEV",
                        "GEVO", "GF", "GFAI", "GFAIW", "GFF", "GFI", "GFL", "GFR", "GFS", "GGAL", "GGB", "GGG", "GGN",
                        "GGR", "GGROW", "GGT", "GGZ", "GH", "GHC", "GHG", "GHI", "GHLD", "GHM", "GHRS", "GHY", "GIB",
                        "GIC", "GIFI", "GIFT", "GIG", "GIGGU", "GIGM", "GIII", "GIL", "GILD", "GILT", "GIPR", "GIS",
                        "GITS", "GJP", "GJR", "GJS", "GKOS", "GL", "GLAD", "GLADZ", "GLBE", "GLBS", "GLBZ", "GLDD",
                        "GLDG",
                        "GLE", "GLMD", "GLNG", "GLO", "GLOB", "GLOP", "GLP", "GLPG", "GLPI", "GLQ", "GLRE", "GLSI",
                        "GLTO",
                        "GLU", "GLUE", "GLV", "GLW", "GLXG", "GLYC", "GM", "GMAB", "GME", "GMED", "GMGI", "GMHS", "GMM",
                        "GMRE", "GMS", "GNE", "GNFT", "GNK", "GNL", "GNLN", "GNLX", "GNPX", "GNRC", "GNS", "GNSS",
                        "GNT",
                        "GNTA", "GNTX", "GNTY", "GNW", "GO", "GOCO", "GOF", "GOGL", "GOGO", "GOLD", "GOLF", "GOOD",
                        "GOODN", "GOODO", "GOOG", "GOOGL", "GOOS", "GORO", "GORV", "GOSS", "GOTU", "GOVX", "GOVXW",
                        "GP",
                        "GPAT", "GPATW", "GPC", "GPCR", "GPI", "GPJA", "GPK", "GPMT", "GPN", "GPOR", "GPRE", "GPRK",
                        "GPRO", "GPUS", "GRAB", "GRABW", "GRAF", "GRAL", "GRBK", "GRC", "GRCE", "GRDN", "GREE", "GREEL",
                        "GRF", "GRFS", "GRFX", "GRI", "GRMN", "GRND", "GRNQ", "GRNT", "GRO", "GROV", "GROW", "GROY",
                        "GRPN", "GRRR", "GRRRW", "GRVY", "GRWG", "GRX", "GRYP", "GS", "GSAT", "GSBC", "GSBD", "GSHD",
                        "GSHRU", "GSIT", "GSIW", "GSK", "GSL", "GSM", "GSRT", "GSRTR", "GSRTU", "GSUN", "GT", "GTBP",
                        "GTE", "GTEC", "GTES", "GTI", "GTIM", "GTLB", "GTLS", "GTN", "GTX", "GTY", "GUG", "GURE", "GUT",
                        "GUTS", "GV", "GVA", "GVH", "GWAV", "GWH", "GWRE", "GWRS", "GWW", "GXAI", "GXO", "GYRE", "GYRO",
                        "H", "HAE", "HAFC", "HAFN", "HAIN", "HAL", "HALO", "HAO", "HAS", "HASI", "HAYW", "HBAN",
                        "HBANL",
                        "HBANM", "HBANP", "HBB", "HBCP", "HBI", "HBIO", "HBM", "HBNC", "HBT", "HCA", "HCAI", "HCAT",
                        "HCC",
                        "HCI", "HCKT", "HCM", "HCSG", "HCTI", "HCWB", "HCWC", "HCXY", "HD", "HDB", "HDL", "HDSN", "HE",
                        "HEES", "HEI", "HELE", "HEPA", "HEPS", "HEQ", "HES", "HESM", "HFBL", "HFFG", "HFRO", "HFWA",
                        "HG",
                        "HGBL", "HGLB", "HGTY", "HGV", "HHH", "HHS", "HI", "HIFS", "HIG", "HIHO", "HII", "HIMS", "HIMX",
                        "HIO", "HIPO", "HIT", "HITI", "HIVE", "HIW", "HIX", "HKD", "HKIT", "HKPD", "HL", "HLF", "HLI",
                        "HLIO", "HLIT", "HLLY", "HLMN", "HLN", "HLNE", "HLP", "HLT", "HLVX", "HLX", "HLXB", "HMC",
                        "HMN",
                        "HMR", "HMST", "HMY", "HNI", "HNNA", "HNNAZ", "HNRG", "HNST", "HNVR", "HNW", "HOFT", "HOFV",
                        "HOFVW", "HOG", "HOLO", "HOLOW", "HOLX", "HOMB", "HON", "HOND", "HONDU", "HONDW", "HONE",
                        "HOOD",
                        "HOOK", "HOPE", "HOTH", "HOUR", "HOUS", "HOV", "HOVNP", "HOVR", "HOVRW", "HOWL", "HP", "HPAI",
                        "HPE", "HPF", "HPH", "HPI", "HPK", "HPKEW", "HPP", "HPQ", "HPS", "HQH", "HQI", "HQL", "HQY",
                        "HR",
                        "HRB", "HRI", "HRL", "HRMY", "HROW", "HROWL", "HROWM", "HRTG", "HRTX", "HRZN", "HSAI", "HSBC",
                        "HSCS", "HSDT", "HSHP", "HSIC", "HSII", "HSON", "HSPO", "HSPOR", "HST", "HSTM", "HSY", "HTB",
                        "HTBK", "HTCO", "HTCR", "HTD", "HTFC", "HTGC", "HTH", "HTHT", "HTLD", "HTLM", "HTOO", "HTZ",
                        "HTZWW", "HUBB", "HUBC", "HUBCW", "HUBG", "HUBS", "HUDI", "HUHU", "HUIZ", "HUM", "HUMA",
                        "HUMAW",
                        "HUN", "HURA", "HURC", "HURN", "HUSA", "HUT", "HUYA", "HVII", "HVIIR", "HVIIU", "HVT", "HWBK",
                        "HWC", "HWCPZ", "HWH", "HWKN", "HWM", "HXHX", "HXL", "HY", "HYAC", "HYFM", "HYI", "HYLN",
                        "HYMC",
                        "HYMCL", "HYMCW", "HYPR", "HYT", "HZO", "I", "IAC", "IAE", "IAF", "IAG", "IART", "IAS", "IAUX",
                        "IBAC", "IBACR", "IBCP", "IBEX", "IBG", "IBIO", "IBKR", "IBM", "IBN", "IBO", "IBOC", "IBP",
                        "IBRX",
                        "IBTA", "ICAD", "ICCC", "ICCM", "ICCT", "ICE", "ICFI", "ICG", "ICHR", "ICL", "ICLR", "ICMB",
                        "ICON", "ICR", "ICU", "ICUCW", "ICUI", "IDA", "IDAI", "IDCC", "IDE", "IDN", "IDR", "IDT",
                        "IDXX",
                        "IDYA", "IE", "IEP", "IESC", "IEX", "IFBD", "IFF", "IFN", "IFRX", "IFS", "IGA", "IGC", "IGD",
                        "IGI", "IGIC", "IGMS", "IGR", "IGT", "IH", "IHD", "IHG", "IHRT", "IHS", "IHT", "IIF", "III",
                        "IIIN", "IIIV", "IIM", "IINN", "IIPR", "IKNA", "IKT", "ILAG", "ILLR", "ILLRW", "ILMN", "ILPT",
                        "IMAB", "IMAX", "IMCC", "IMCR", "IMG", "IMKTA", "IMMP", "IMMR", "IMMX", "IMNM", "IMNN", "IMO",
                        "IMOS", "IMPP", "IMPPP", "IMRN", "IMRX", "IMTE", "IMTX", "IMUX", "IMVT", "IMXI", "INAB", "INBK",
                        "INBKZ", "INBS", "INBX", "INCR", "INCY", "INDB", "INDI", "INDO", "INDP", "INDV", "INFA", "INFU",
                        "INFY", "ING", "INGM", "INGN", "INGR", "INHD", "INKT", "INLF", "INLX", "INM", "INMB", "INMD",
                        "INN", "INNV", "INO", "INOD", "INR", "INSE", "INSG", "INSM", "INSP", "INSW", "INTA", "INTC",
                        "INTG", "INTJ", "INTR", "INTS", "INTT", "INTU", "INTZ", "INUV", "INV", "INVA", "INVE", "INVH",
                        "INVX", "INVZ", "INVZW", "INZY", "IOBT", "IONQ", "IONR", "IONS", "IOR", "IOSP", "IOT", "IOTR",
                        "IOVA", "IP", "IPA", "IPAR", "IPDN", "IPG", "IPGP", "IPHA", "IPI", "IPM", "IPSC", "IPW", "IPWR",
                        "IPX", "IQ", "IQI", "IQV", "IR", "IRBT", "IRD", "IRDM", "IREN", "IRIX", "IRM", "IRMD", "IROH",
                        "IROHR", "IROHW", "IRON", "IROQ", "IRS", "IRT", "IRTC", "IRWD", "ISD", "ISPC", "ISPO", "ISPR",
                        "ISRG", "ISRL", "ISRLW", "ISSC", "ISTR", "IT", "ITGR", "ITIC", "ITOS", "ITP", "ITRG", "ITRI",
                        "ITRM", "ITRN", "ITT", "ITUB", "ITW", "IVA", "IVCA", "IVDA", "IVP", "IVR", "IVT", "IVVD", "IVZ",
                        "IX", "IXHL", "IZEA", "IZM", "J", "JACK", "JACS", "JAGX", "JAKK", "JAMF", "JANX", "JAZZ",
                        "JBDI",
                        "JBGS", "JBHT", "JBI", "JBL", "JBLU", "JBSS", "JBTM", "JCE", "JCI", "JCSE", "JCTC", "JD",
                        "JDZG",
                        "JEF", "JELD", "JEQ", "JFB", "JFBR", "JFBRW", "JFIN", "JFR", "JFU", "JG", "JGH", "JHG", "JHI",
                        "JHS", "JHX", "JILL", "JJSF", "JKHY", "JKS", "JL", "JLL", "JLS", "JMIA", "JMM", "JMSB", "JNJ",
                        "JNPR", "JNVR", "JOB", "JOBY", "JOE", "JOF", "JOUT", "JOYY", "JPC", "JPI", "JPM", "JQC", "JRI",
                        "JRS", "JRSH", "JRVR", "JSM", "JSPR", "JTAI", "JUNE", "JUNS", "JVA", "JWEL", "JWN", "JXG",
                        "JXN",
                        "JYD", "JYNT", "JZ", "JZXN", "K", "KAI", "KALA", "KALU", "KALV", "KAPA", "KAR", "KARO", "KAVL",
                        "KB", "KBDC", "KBH", "KBR", "KBSX", "KC", "KD", "KDLY", "KDLYW", "KDP", "KE", "KELYA", "KELYB",
                        "KEN", "KEP", "KEQU", "KEX", "KEY", "KEYS", "KF", "KFFB", "KFII", "KFIIR", "KFIIU", "KFRC",
                        "KFS",
                        "KFY", "KGC", "KGEI", "KGS", "KHC", "KIDS", "KIDZ", "KIDZW", "KIM", "KIND", "KINS", "KIO",
                        "KIRK",
                        "KITT", "KITTW", "KKR", "KKRS", "KLAC", "KLC", "KLG", "KLIC", "KLRS", "KLTO", "KLTOW", "KLTR",
                        "KLXE", "KMB", "KMDA", "KMI", "KMPB", "KMPR", "KMT", "KMTS", "KMX", "KN", "KNDI", "KNF", "KNOP",
                        "KNSA", "KNSL", "KNTK", "KNW", "KNX", "KO", "KOD", "KODK", "KOF", "KOP", "KOPN", "KORE", "KOS",
                        "KOSS", "KPLT", "KPLTW", "KPRX", "KPTI", "KR", "KRC", "KREF", "KRG", "KRKR", "KRMD", "KRMN",
                        "KRNT", "KRNY", "KRO", "KRON", "KROS", "KRP", "KRRO", "KRT", "KRUS", "KRYS", "KSCP", "KSPI",
                        "KSS",
                        "KT", "KTB", "KTCC", "KTF", "KTH", "KTN", "KTOS", "KTTA", "KTTAW", "KUKE", "KULR", "KURA",
                        "KVACW",
                        "KVHI", "KVUE", "KVYO", "KW", "KWE", "KWESW", "KWR", "KXIN", "KYMR", "KYN", "KYTX", "KZIA",
                        "KZR",
                        "L", "LAB", "LAC", "LAD", "LADR", "LAES", "LAKE", "LAMR", "LANC", "LAND", "LANDM", "LANDO",
                        "LANDP", "LANV", "LAR", "LARK", "LASE", "LASR", "LAUR", "LAW", "LAZ", "LAZR", "LB", "LBGJ",
                        "LBRDA", "LBRDK", "LBRDP", "LBRT", "LBTYA", "LBTYB", "LBTYK", "LC", "LCFY", "LCFYW", "LCID",
                        "LCII", "LCNB", "LCTX", "LCUT", "LDI", "LDOS", "LDP", "LDTC", "LDTCW", "LDWY", "LE", "LEA",
                        "LECO",
                        "LEDS", "LEE", "LEG", "LEGH", "LEGN", "LEGT", "LEN", "LENZ", "LEO", "LESL", "LEU", "LEVI",
                        "LEXX",
                        "LEXXW", "LFCR", "LFMD", "LFMDP", "LFST", "LFT", "LFUS", "LFVN", "LFWD", "LGCB", "LGCL", "LGCY",
                        "LGHL", "LGHLW", "LGI", "LGIH", "LGL", "LGMK", "LGND", "LGO", "LGPS", "LGVN", "LH", "LHSW",
                        "LHX",
                        "LI", "LICN", "LIDR", "LIDRW", "LIEN", "LIF", "LII", "LILA", "LILAK", "LIN", "LINC", "LIND",
                        "LINE", "LINK", "LION", "LIPO", "LIQT", "LITB", "LITE", "LITM", "LIVE", "LIVN", "LIXT", "LKFN",
                        "LKQ", "LLY", "LLYVA", "LLYVK", "LMAT", "LMB", "LMFA", "LMND", "LMNR", "LMT", "LNC", "LND",
                        "LNG",
                        "LNKB", "LNKS", "LNN", "LNSR", "LNT", "LNTH", "LNW", "LNZA", "LNZAW", "LOAN", "LOAR", "LOB",
                        "LOBO", "LOCL", "LOCO", "LODE", "LOGC", "LOGI", "LOKV", "LOKVU", "LOMA", "LOOP", "LOPE", "LOT",
                        "LOVE", "LOW", "LPA", "LPAA", "LPAAU", "LPAAW", "LPBB", "LPBBU", "LPBBW", "LPCN", "LPG", "LPL",
                        "LPLA", "LPRO", "LPSN", "LPTH", "LPTX", "LPX", "LQDA", "LQDT", "LRCX", "LRE", "LRFC", "LRHC",
                        "LRMR", "LRN", "LSAK", "LSB", "LSBK", "LSBPW", "LSCC", "LSE", "LSEA", "LSEAW", "LSF", "LSH",
                        "LSPD", "LSTA", "LSTR", "LTBR", "LTC", "LTH", "LTM", "LTRN", "LTRX", "LTRY", "LTRYW", "LU",
                        "LUCD",
                        "LUCK", "LUCY", "LUCYW", "LUD", "LULU", "LUMN", "LUNG", "LUNR", "LUV", "LVLU", "LVO", "LVRO",
                        "LVROW", "LVS", "LVTX", "LVWR", "LW", "LWAY", "LWLG", "LX", "LXEH", "LXEO", "LXFR", "LXP",
                        "LXRX",
                        "LXU", "LYB", "LYEL", "LYFT", "LYG", "LYRA", "LYTS", "LYV", "LZ", "LZB", "LZM", "LZMH", "M",
                        "MA",
                        "MAA", "MAC", "MAG", "MAGN", "MAIA", "MAIN", "MAMA", "MAMO", "MAN", "MANH", "MANU", "MAPS",
                        "MAPSW", "MAR", "MARA", "MARPS", "MAS", "MASI", "MASK", "MASS", "MAT", "MATH", "MATV", "MATW",
                        "MATX", "MAV", "MAX", "MAXN", "MAYA", "MAYAU", "MAYS", "MAZE", "MB", "MBAV", "MBAVU", "MBAVW",
                        "MBBC", "MBC", "MBCN", "MBI", "MBIN", "MBINL", "MBINM", "MBINN", "MBIO", "MBLY", "MBNKP",
                        "MBOT",
                        "MBRX", "MBUU", "MBWM", "MBX", "MC", "MCB", "MCBS", "MCD", "MCFT", "MCHP", "MCHPP", "MCHX",
                        "MCI",
                        "MCK", "MCN", "MCO", "MCR", "MCRB", "MCRI", "MCRP", "MCS", "MCTR", "MCVT", "MCW", "MCY", "MD",
                        "MDAI", "MDAIW", "MDB", "MDBH", "MDCX", "MDCXW", "MDGL", "MDIA", "MDLZ", "MDRR", "MDT", "MDU",
                        "MDV", "MDWD", "MDXG", "MDXH", "MEC", "MED", "MEDP", "MEG", "MEGI", "MEGL", "MEI", "MEIP",
                        "MELI",
                        "MEOH", "MER", "MERC", "MESA", "MESO", "MET", "META", "METC", "METCB", "METCL", "METCZ", "MFA",
                        "MFAN", "MFAO", "MFC", "MFG", "MFH", "MFI", "MFIC", "MFICL", "MFIN", "MFM", "MG", "MGA", "MGEE",
                        "MGF", "MGIC", "MGIH", "MGLD", "MGM", "MGNI", "MGNX", "MGPI", "MGR", "MGRB", "MGRC", "MGRD",
                        "MGRE", "MGRM", "MGRX", "MGTX", "MGX", "MGY", "MGYR", "MHD", "MHF", "MHH", "MHI", "MHK", "MHLA",
                        "MHLD", "MHN", "MHNC", "MHO", "MHUA", "MI", "MIDD", "MIGI", "MIMI", "MIN", "MIND", "MIO", "MIR",
                        "MIRA", "MIRM", "MIST", "MITK", "MITN", "MITP", "MITQ", "MITT", "MIY", "MKC", "MKDW", "MKDWW",
                        "MKL", "MKSI", "MKTW", "MKTX", "MKZR", "MLAB", "MLAC", "MLACR", "MLACU", "MLCO", "MLEC", "MLGO",
                        "MLI", "MLKN", "MLM", "MLNK", "MLP", "MLR", "MLSS", "MLTX", "MLYS", "MMA", "MMC", "MMD", "MMI",
                        "MMLP", "MMM", "MMS", "MMSI", "MMT", "MMU", "MMYT", "MNDO", "MNDR", "MNDY", "MNKD", "MNMD",
                        "MNOV",
                        "MNPR", "MNR", "MNRO", "MNSB", "MNSO", "MNST", "MNTK", "MNTS", "MNTSW", "MNY", "MNYWW", "MO",
                        "MOB", "MOBBW", "MOBX", "MOD", "MODD", "MODG", "MODV", "MOFG", "MOGO", "MOGU", "MOH", "MOLN",
                        "MOMO", "MORN", "MOS", "MOV", "MOVE", "MP", "MPA", "MPAA", "MPB", "MPC", "MPLX", "MPTI", "MPU",
                        "MPV", "MPW", "MPWR", "MPX", "MQ", "MQT", "MQY", "MRAM", "MRBK", "MRC", "MRCC", "MRCY", "MREO",
                        "MRIN", "MRK", "MRKR", "MRM", "MRNA", "MRNO", "MRNOW", "MRP", "MRSN", "MRT", "MRTN", "MRUS",
                        "MRVI", "MRVL", "MRX", "MS", "MSA", "MSAI", "MSB", "MSBI", "MSBIP", "MSC", "MSCI", "MSD",
                        "MSDL",
                        "MSEX", "MSFT", "MSGE", "MSGM", "MSGS", "MSI", "MSIF", "MSM", "MSN", "MSPR", "MSPRW", "MSPRZ",
                        "MSS", "MSTR", "MSW", "MT", "MTA", "MTAL", "MTB", "MTC", "MTCH", "MTD", "MTDR", "MTEK", "MTEKW",
                        "MTEN", "MTEX", "MTG", "MTH", "MTLS", "MTN", "MTNB", "MTR", "MTRN", "MTRX", "MTSI", "MTSR",
                        "MTUS",
                        "MTVA", "MTW", "MTX", "MTZ", "MU", "MUA", "MUC", "MUE", "MUFG", "MUJ", "MULN", "MUR", "MURA",
                        "MUSA", "MUX", "MVBF", "MVF", "MVIS", "MVO", "MVST", "MVSTW", "MVT", "MWA", "MWG", "MWYN", "MX",
                        "MXC", "MXCT", "MXE", "MXF", "MXL", "MYD", "MYE", "MYFW", "MYGN", "MYI", "MYN", "MYND", "MYNZ",
                        "MYO", "MYPS", "MYPSW", "MYRG", "MYSZ", "MYTE", "N", "NA", "NAAS", "NABL", "NAC", "NAD", "NAGE",
                        "NAII", "NAK", "NAMI", "NAMS", "NAMSW", "NAN", "NAOV", "NAT", "NATH", "NATL", "NATR", "NAUT",
                        "NAVI", "NAYA", "NAZ", "NB", "NBB", "NBBK", "NBH", "NBHC", "NBIS", "NBIX", "NBN", "NBR", "NBTB",
                        "NBTX", "NBXG", "NBY", "NC", "NCA", "NCDL", "NCEW", "NCI", "NCIQ", "NCL", "NCLH", "NCMI",
                        "NCNA",
                        "NCNO", "NCPL", "NCRA", "NCSM", "NCT", "NCTY", "NCV", "NCZ", "NDAQ", "NDLS", "NDMO", "NDRA",
                        "NDSN", "NE", "NEA", "NECB", "NEE", "NEGG", "NEHC", "NEHCW", "NEM", "NEN", "NEO", "NEOG",
                        "NEON",
                        "NEOV", "NEOVW", "NEPH", "NERV", "NESR", "NESRW", "NET", "NETD", "NETDW", "NEU", "NEUE", "NEUP",
                        "NEWP", "NEWT", "NEWTG", "NEWTH", "NEWTI", "NEWTZ", "NEXA", "NEXN", "NEXT", "NFBK", "NFE",
                        "NFG",
                        "NFGC", "NFJ", "NFLX", "NG", "NGD", "NGG", "NGL", "NGNE", "NGS", "NGVC", "NGVT", "NHC", "NHI",
                        "NHIC", "NHICU", "NHICW", "NHPAP", "NHPBP", "NHS", "NHTC", "NI", "NIC", "NICE", "NIE", "NIM",
                        "NINE", "NIO", "NIOBW", "NIPG", "NISN", "NITO", "NIU", "NIVF", "NIXX", "NIXXW", "NJR", "NKE",
                        "NKSH", "NKTR", "NKTX", "NKX", "NL", "NLOP", "NLSP", "NLSPW", "NLY", "NMAI", "NMAX", "NMCO",
                        "NMFC", "NMFCZ", "NMG", "NMI", "NMIH", "NML", "NMM", "NMR", "NMRA", "NMRK", "NMS", "NMT",
                        "NMTC",
                        "NMZ", "NN", "NNAVW", "NNBR", "NNDM", "NNE", "NNI", "NNN", "NNNN", "NNOX", "NNVC", "NNY", "NOA",
                        "NOAH", "NOC", "NODK", "NOEM", "NOEMR", "NOG", "NOK", "NOM", "NOMD", "NOTE", "NOTV", "NOV",
                        "NOVA",
                        "NOVT", "NOW", "NPACU", "NPB", "NPCE", "NPCT", "NPFD", "NPK", "NPKI", "NPO", "NPV", "NPWR",
                        "NQP",
                        "NRC", "NRDS", "NRDY", "NREF", "NRG", "NRGV", "NRIM", "NRIX", "NRK", "NRO", "NRP", "NRSN",
                        "NRSNW",
                        "NRT", "NRUC", "NRXP", "NRXPW", "NRXS", "NSA", "NSC", "NSIT", "NSP", "NSPR", "NSSC", "NSTS",
                        "NSYS", "NTAP", "NTB", "NTCL", "NTCT", "NTES", "NTGR", "NTHI", "NTIC", "NTIP", "NTLA", "NTNX",
                        "NTR", "NTRA", "NTRB", "NTRP", "NTRS", "NTRSO", "NTST", "NTWK", "NTWO", "NTWOU", "NTWOW", "NTZ",
                        "NU", "NUE", "NUKK", "NUKKW", "NURO", "NUS", "NUTX", "NUV", "NUVB", "NUVL", "NUW", "NUWE",
                        "NVA",
                        "NVAWW", "NVAX", "NVCR", "NVCT", "NVDA", "NVEC", "NVEE", "NVFY", "NVG", "NVGS", "NVMI", "NVNI",
                        "NVNIW", "NVNO", "NVO", "NVR", "NVRI", "NVS", "NVST", "NVT", "NVTS", "NVVE", "NVVEW", "NVX",
                        "NWBI", "NWE", "NWFL", "NWG", "NWGL", "NWL", "NWN", "NWPX", "NWS", "NWSA", "NWTG", "NWTN",
                        "NWTNW",
                        "NX", "NXC", "NXDT", "NXE", "NXG", "NXGL", "NXGLW", "NXJ", "NXL", "NXN", "NXP", "NXPI", "NXPL",
                        "NXPLW", "NXRT", "NXST", "NXT", "NXTC", "NXTT", "NXXT", "NYAX", "NYC", "NYMT", "NYMTG", "NYMTI",
                        "NYMTL", "NYMTM", "NYMTN", "NYMTZ", "NYT", "NYXH", "NZF", "O", "OABI", "OACC", "OACCU", "OAK",
                        "OAKU", "OAKUR", "OAKUW", "OB", "OBDC", "OBE", "OBIO", "OBK", "OBLG", "OBT", "OC", "OCC",
                        "OCCI",
                        "OCCIM", "OCCIN", "OCCIO", "OCFC", "OCFCP", "OCFT", "OCG", "OCGN", "OCS", "OCSL", "OCTO",
                        "OCUL",
                        "OCX", "ODC", "ODD", "ODFL", "ODP", "ODV", "ODVWZ", "ODYS", "OEC", "OESX", "OFG", "OFIX",
                        "OFLX",
                        "OFS", "OGE", "OGEN", "OGI", "OGN", "OGS", "OHI", "OI", "OIA", "OII", "OIS", "OKE", "OKLO",
                        "OKTA",
                        "OKUR", "OKYO", "OLB", "OLED", "OLLI", "OLMA", "OLN", "OLO", "OLP", "OLPX", "OM", "OMAB", "OMC",
                        "OMCC", "OMCL", "OMER", "OMEX", "OMF", "OMH", "OMI", "ON", "ONB", "ONBPO", "ONBPP", "ONC",
                        "ONCO",
                        "ONCY", "ONDS", "ONEG", "ONEW", "ONFO", "ONIT", "ONL", "ONMD", "ONON", "ONTF", "ONTO", "OOMA",
                        "OP", "OPAD", "OPAL", "OPBK", "OPCH", "OPEN", "OPFI", "OPHC", "OPI", "OPINL", "OPK", "OPOF",
                        "OPP",
                        "OPRA", "OPRT", "OPRX", "OPTN", "OPTT", "OPTX", "OPTXW", "OPXS", "OPY", "OR", "ORA", "ORC",
                        "ORCL",
                        "ORGN", "ORGNW", "ORGO", "ORI", "ORIC", "ORIS", "ORKA", "ORKT", "ORLA", "ORLY", "ORMP", "ORN",
                        "ORRF", "OS", "OSBC", "OSCR", "OSIS", "OSK", "OSPN", "OSRH", "OSRHW", "OSS", "OST", "OSTX",
                        "OSUR",
                        "OSW", "OTEX", "OTIS", "OTLK", "OTLY", "OTRK", "OTTR", "OUST", "OUSTW", "OUSTZ", "OUT", "OVBC",
                        "OVID", "OVLY", "OVV", "OWL", "OWLT", "OXBR", "OXLC", "OXLCG", "OXLCI", "OXLCL", "OXLCN",
                        "OXLCO",
                        "OXLCP", "OXLCZ", "OXM", "OXSQ", "OXSQG", "OXSQZ", "OXY", "OZ", "OZK", "OZKAP", "P", "PAA",
                        "PAAS",
                        "PAC", "PACB", "PACK", "PACS", "PAG", "PAGP", "PAGS", "PAHC", "PAI", "PAL", "PALI", "PAM",
                        "PAMT",
                        "PANL", "PANW", "PAPL", "PAR", "PARA", "PARAA", "PARR", "PASG", "PATH", "PATK", "PAVM", "PAVMZ",
                        "PAVS", "PAX", "PAXS", "PAY", "PAYC", "PAYO", "PAYS", "PAYX", "PB", "PBA", "PBBK", "PBF",
                        "PBFS",
                        "PBH", "PBHC", "PBI", "PBM", "PBMWW", "PBPB", "PBR", "PBT", "PBYI", "PC", "PCAR", "PCB", "PCF",
                        "PCG", "PCH", "PCK", "PCLA", "PCM", "PCN", "PCOR", "PCQ", "PCRX", "PCSA", "PCSC", "PCT",
                        "PCTTW",
                        "PCTY", "PCVX", "PCYO", "PD", "PDCC", "PDD", "PDEX", "PDFS", "PDI", "PDLB", "PDM", "PDO",
                        "PDPA",
                        "PDS", "PDSB", "PDT", "PDX", "PDYN", "PDYNW", "PEB", "PEBK", "PEBO", "PECO", "PED", "PEG",
                        "PEGA",
                        "PEN", "PENG", "PENN", "PEO", "PEP", "PEPG", "PERF", "PERI", "PESI", "PET", "PETS", "PETWW",
                        "PETZ", "PFAI", "PFBC", "PFD", "PFE", "PFG", "PFGC", "PFH", "PFIS", "PFL", "PFLT", "PFN", "PFO",
                        "PFS", "PFSI", "PFX", "PFXNZ", "PG", "PGC", "PGEN", "PGHL", "PGNY", "PGP", "PGR", "PGRE", "PGY",
                        "PGYWW", "PGZ", "PH", "PHAR", "PHAT", "PHD", "PHG", "PHGE", "PHH", "PHI", "PHIN", "PHIO", "PHK",
                        "PHLT", "PHM", "PHR", "PHT", "PHUN", "PHVS", "PHX", "PI", "PII", "PIII", "PIIIW", "PIM", "PINC",
                        "PINE", "PINS", "PIPR", "PITA", "PITAW", "PJT", "PK", "PKBK", "PKE", "PKG", "PKOH", "PKST",
                        "PKX",
                        "PL", "PLAB", "PLAG", "PLAY", "PLBC", "PLBY", "PLCE", "PLD", "PLG", "PLL", "PLMK", "PLMKU",
                        "PLMKW", "PLMR", "PLNT", "PLOW", "PLPC", "PLRX", "PLRZ", "PLSE", "PLTK", "PLTR", "PLUG", "PLUR",
                        "PLUS", "PLUT", "PLX", "PLXS", "PLYA", "PLYM", "PM", "PMAX", "PMCB", "PMEC", "PMF", "PML",
                        "PMM",
                        "PMN", "PMNT", "PMO", "PMT", "PMTS", "PMTU", "PMTV", "PMVP", "PMX", "PN", "PNBK", "PNC", "PNF",
                        "PNFP", "PNFPP", "PNI", "PNNT", "PNR", "PNRG", "PNTG", "PNW", "POAI", "POCI", "PODC", "PODD",
                        "POET", "POLA", "POLE", "POLEW", "PONY", "POOL", "POR", "POST", "POWI", "POWL", "POWW", "POWWP",
                        "PPBI", "PPBT", "PPC", "PPG", "PPIH", "PPL", "PPSI", "PPT", "PPTA", "PR", "PRA", "PRAA", "PRAX",
                        "PRCH", "PRCT", "PRDO", "PRE", "PRENW", "PRFX", "PRG", "PRGO", "PRGS", "PRH", "PRI", "PRIF",
                        "PRIM", "PRK", "PRKS", "PRLB", "PRLD", "PRM", "PRMB", "PRME", "PRO", "PROF", "PROK", "PROP",
                        "PROV", "PRPH", "PRPL", "PRPO", "PRQR", "PRS", "PRSO", "PRSU", "PRT", "PRTA", "PRTC", "PRTG",
                        "PRTH", "PRTS", "PRU", "PRVA", "PRZO", "PSA", "PSBD", "PSEC", "PSF", "PSFE", "PSHG", "PSIG",
                        "PSIX", "PSMT", "PSN", "PSNL", "PSNY", "PSNYW", "PSO", "PSQH", "PSTG", "PSTL", "PSTV", "PSX",
                        "PT",
                        "PTA", "PTC", "PTCT", "PTEN", "PTGX", "PTHL", "PTIX", "PTIXW", "PTLE", "PTLO", "PTMN", "PTN",
                        "PTON", "PTPI", "PTY", "PUBM", "PUK", "PULM", "PUMP", "PVBC", "PVH", "PVL", "PVLA", "PW", "PWM",
                        "PWOD", "PWP", "PWR", "PX", "PXLW", "PXS", "PXSAW", "PYN", "PYPD", "PYPL", "PYXS", "PZC", "PZG",
                        "PZZA", "Q", "QBTS", "QCOM", "QCRH", "QD", "QDEL", "QETA", "QETAU", "QFIN", "QGEN", "QH",
                        "QIPT",
                        "QLGN", "QLYS", "QMCO", "QMMM", "QNCX", "QNRX", "QNST", "QNTM", "QQQX", "QRHC", "QRVO", "QS",
                        "QSG", "QSI", "QSIAW", "QSR", "QTRX", "QTTB", "QTWO", "QUAD", "QUBT", "QUIK", "QURE", "QVCC",
                        "QVCD", "QVCGA", "QVCGB", "QVCGP", "QXO", "R", "RA", "RAC", "RACE", "RADX", "RAIL", "RAIN",
                        "RAINW", "RAMP", "RAND", "RANG", "RANGU", "RANI", "RAPP", "RAPT", "RARE", "RAVE", "RAY", "RAYA",
                        "RBA", "RBB", "RBBN", "RBC", "RBCAA", "RBKB", "RBLX", "RBNE", "RBOT", "RBRK", "RC", "RCAT",
                        "RCB",
                        "RCC", "RCD", "RCEL", "RCG", "RCI", "RCKT", "RCKTW", "RCKY", "RCL", "RCMT", "RCON", "RCS",
                        "RCT",
                        "RCUS", "RDAC", "RDCM", "RDDT", "RDFN", "RDGT", "RDHL", "RDI", "RDIB", "RDN", "RDNT", "RDUS",
                        "RDVT", "RDW", "RDWR", "RDY", "RDZN", "RDZNW", "REAL", "REAX", "REBN", "RECT", "REE", "REFI",
                        "REFR", "REG", "REGCO", "REGCP", "REGN", "REI", "REKR", "RELI", "RELL", "RELX", "RELY", "RENB",
                        "RENE", "RENEW", "RENT", "REPL", "REPX", "RERE", "RES", "RETO", "REVB", "REVBW", "REVG", "REX",
                        "REXR", "REYN", "REZI", "RF", "RFAI", "RFAIR", "RFI", "RFIL", "RFL", "RFM", "RFMZ", "RGA",
                        "RGC",
                        "RGCO", "RGEN", "RGLD", "RGLS", "RGNX", "RGP", "RGR", "RGS", "RGT", "RGTI", "RGTIW", "RH",
                        "RHI",
                        "RHLD", "RHP", "RICK", "RIG", "RIGL", "RILY", "RILYG", "RILYK", "RILYL", "RILYN", "RILYP",
                        "RILYT",
                        "RILYZ", "RIME", "RIO", "RIOT", "RITM", "RITR", "RIV", "RIVN", "RJF", "RKDA", "RKLB", "RKT",
                        "RL",
                        "RLAY", "RLGT", "RLI", "RLJ", "RLMD", "RLTY", "RLX", "RLYB", "RM", "RMAX", "RMBI", "RMBL",
                        "RMBS",
                        "RMCF", "RMCO", "RMD", "RMI", "RMM", "RMMZ", "RMNI", "RMR", "RMSG", "RMT", "RMTI", "RNA",
                        "RNAC",
                        "RNAZ", "RNG", "RNGR", "RNP", "RNR", "RNST", "RNTX", "RNW", "RNXT", "ROAD", "ROCK", "ROG",
                        "ROIV",
                        "ROK", "ROKU", "ROL", "ROLR", "ROMA", "ROOT", "ROP", "ROST", "RPAY", "RPD", "RPID", "RPM",
                        "RPRX",
                        "RPT", "RPTX", "RQI", "RR", "RRBI", "RRC", "RRGB", "RRR", "RRX", "RS", "RSF", "RSG", "RSI",
                        "RSKD",
                        "RSLS", "RSSS", "RSVR", "RSVRW", "RTC", "RTO", "RTX", "RUM", "RUMBW", "RUN", "RUSHA", "RUSHB",
                        "RVLV", "RVMD", "RVMDW", "RVP", "RVPH", "RVPHW", "RVSB", "RVSN", "RVSNW", "RVT", "RVTY", "RVYL",
                        "RWAY", "RWAYL", "RWAYZ", "RWT", "RWTN", "RWTO", "RWTP", "RXO", "RXRX", "RXST", "RXT", "RY",
                        "RYAAY", "RYAM", "RYAN", "RYDE", "RYET", "RYI", "RYN", "RYTM", "RZB", "RZC", "RZLT", "RZLV",
                        "RZLVW", "S", "SA", "SABA", "SABR", "SABS", "SACH", "SAFE", "SAFT", "SAG", "SAGE", "SAGT",
                        "SAH",
                        "SAIA", "SAIC", "SAIH", "SAIHW", "SAIL", "SAJ", "SAM", "SAMG", "SAN", "SANA", "SAND", "SANG",
                        "SANM", "SANW", "SAP", "SAR", "SARO", "SAT", "SATL", "SATS", "SATX", "SAVA", "SAY", "SAZ", "SB",
                        "SBAC", "SBC", "SBCF", "SBCWW", "SBET", "SBEV", "SBFG", "SBFM", "SBFMW", "SBGI", "SBH", "SBI",
                        "SBLK", "SBR", "SBRA", "SBS", "SBSI", "SBSW", "SBUX", "SBXD", "SCCC", "SCCD", "SCCE", "SCCF",
                        "SCCG", "SCCO", "SCD", "SCE", "SCHL", "SCHW", "SCI", "SCKT", "SCL", "SCLX", "SCLXW", "SCM",
                        "SCNI",
                        "SCNX", "SCOR", "SCPH", "SCS", "SCSC", "SCVL", "SCWO", "SCYX", "SD", "SDA", "SDAWW", "SDGR",
                        "SDHC", "SDHIU", "SDHY", "SDOT", "SDRL", "SDST", "SDSTW", "SE", "SEAL", "SEAT", "SEATW", "SEB",
                        "SEDG", "SEE", "SEED", "SEER", "SEG", "SEI", "SEIC", "SELF", "SELX", "SEM", "SEMR", "SENEA",
                        "SENEB", "SENS", "SEPN", "SER", "SERA", "SERV", "SES", "SEVN", "SEZL", "SF", "SFB", "SFBC",
                        "SFBS",
                        "SFD", "SFHG", "SFIX", "SFL", "SFM", "SFNC", "SFST", "SFWL", "SG", "SGA", "SGBX", "SGC", "SGD",
                        "SGHC", "SGHT", "SGI", "SGLY", "SGMA", "SGML", "SGMO", "SGMT", "SGN", "SGRP", "SGRY", "SGU",
                        "SHAK", "SHBI", "SHC", "SHCO", "SHEL", "SHEN", "SHFS", "SHFSW", "SHG", "SHIM", "SHIP", "SHLS",
                        "SHMD", "SHMDW", "SHO", "SHOO", "SHOP", "SHOT", "SHOTW", "SHPH", "SHW", "SHYF", "SIBN", "SID",
                        "SIDU", "SIEB", "SIF", "SIFY", "SIG", "SIGA", "SIGI", "SIGIP", "SII", "SILA", "SILC", "SILO",
                        "SIM", "SIMA", "SIMAU", "SIMAW", "SIMO", "SINT", "SION", "SIRI", "SISI", "SITC", "SITE", "SITM",
                        "SJ", "SJM", "SJT", "SJW", "SKBL", "SKE", "SKIL", "SKIN", "SKK", "SKLZ", "SKM", "SKT", "SKWD",
                        "SKX", "SKY", "SKYE", "SKYH", "SKYQ", "SKYT", "SKYW", "SKYX", "SLAB", "SLB", "SLDB", "SLDP",
                        "SLDPW", "SLE", "SLF", "SLG", "SLGL", "SLGN", "SLI", "SLM", "SLMBP", "SLN", "SLND", "SLNG",
                        "SLNH",
                        "SLNHP", "SLNO", "SLP", "SLQT", "SLRC", "SLRN", "SLRX", "SLS", "SLSN", "SLSR", "SLVM", "SLXN",
                        "SLXNW", "SM", "SMA", "SMBC", "SMBK", "SMC", "SMCI", "SMFG", "SMG", "SMHI", "SMID", "SMLR",
                        "SMMT",
                        "SMP", "SMPL", "SMR", "SMRT", "SMSI", "SMTC", "SMTI", "SMTK", "SMWB", "SMX", "SMXT", "SMXWW",
                        "SN",
                        "SNA", "SNAL", "SNAP", "SNBR", "SNCR", "SNCRL", "SNCY", "SND", "SNDA", "SNDK", "SNDL", "SNDR",
                        "SNDX", "SNES", "SNEX", "SNFCA", "SNGX", "SNN", "SNOA", "SNOW", "SNPS", "SNPX", "SNRE", "SNSE",
                        "SNT", "SNTG", "SNTI", "SNV", "SNWV", "SNX", "SNY", "SNYR", "SO", "SOAR", "SOBO", "SOBR", "SOC",
                        "SOFI", "SOGP", "SOHO", "SOHOB", "SOHOO", "SOHU", "SOJC", "SOJD", "SOJE", "SOJF", "SOL", "SOLV",
                        "SON", "SOND", "SONDW", "SONM", "SONN", "SONO", "SONY", "SOPA", "SOPH", "SOR", "SOS", "SOTK",
                        "SOUN", "SOUNW", "SOWG", "SPAI", "SPB", "SPCB", "SPCE", "SPE", "SPFI", "SPG", "SPGI", "SPH",
                        "SPHL", "SPHR", "SPIR", "SPKL", "SPKLW", "SPLP", "SPMA", "SPMC", "SPNS", "SPNT", "SPOK", "SPOT",
                        "SPPL", "SPR", "SPRB", "SPRC", "SPRO", "SPRU", "SPRY", "SPSC", "SPT", "SPTN", "SPWH", "SPWR",
                        "SPWRW", "SPXC", "SPXX", "SQFT", "SQFTP", "SQFTW", "SQM", "SQNS", "SR", "SRAD", "SRBK", "SRCE",
                        "SRDX", "SRE", "SREA", "SRFM", "SRG", "SRI", "SRL", "SRM", "SRPT", "SRRK", "SRTS", "SRV",
                        "SRZN",
                        "SRZNW", "SSB", "SSBI", "SSBK", "SSD", "SSII", "SSKN", "SSL", "SSNC", "SSP", "SSRM", "SSSS",
                        "SSSSL", "SST", "SSTI", "SSTK", "SSY", "SSYS", "ST", "STAA", "STAG", "STAI", "STAK", "STBA",
                        "STBX", "STC", "STE", "STEC", "STEL", "STEM", "STEP", "STEW", "STFS", "STG", "STGW", "STHO",
                        "STI",
                        "STIM", "STK", "STKH", "STKL", "STKS", "STLA", "STLD", "STM", "STN", "STNE", "STNG", "STOK",
                        "STR",
                        "STRA", "STRF", "STRK", "STRL", "STRM", "STRO", "STRR", "STRRP", "STRS", "STRT", "STRW", "STSS",
                        "STSSW", "STT", "STTK", "STVN", "STWD", "STX", "STXS", "STZ", "SU", "SUGP", "SUI", "SUN",
                        "SUNE",
                        "SUNS", "SUP", "SUPN", "SUPV", "SURG", "SUUN", "SUZ", "SVC", "SVCC", "SVCCU", "SVCCW", "SVCO",
                        "SVII", "SVIIR", "SVIIU", "SVIIW", "SVM", "SVRA", "SVRE", "SVT", "SVV", "SW", "SWAG", "SWAGW",
                        "SWBI", "SWIM", "SWIN", "SWK", "SWKH", "SWKHL", "SWKS", "SWTX", "SWVL", "SWVLW", "SWX", "SWZ",
                        "SXC", "SXI", "SXT", "SXTC", "SXTP", "SXTPW", "SY", "SYBT", "SYBX", "SYF", "SYK", "SYM", "SYNA",
                        "SYNX", "SYPR", "SYRE", "SYT", "SYTA", "SYTAW", "SYY", "SZZLU", "T", "TAC", "TACHU", "TACT",
                        "TAIT", "TAK", "TAL", "TALK", "TALKW", "TALO", "TANH", "TAOP", "TAP", "TARA", "TARS", "TASK",
                        "TATT", "TAVI", "TAVIR", "TAVIU", "TAYD", "TBB", "TBBB", "TBBK", "TBCH", "TBH", "TBI", "TBLA",
                        "TBLD", "TBMCR", "TBN", "TBPH", "TBRG", "TC", "TCBI", "TCBIO", "TCBK", "TCBS", "TCBX", "TCI",
                        "TCMD", "TCOM", "TCPC", "TCRT", "TCRX", "TCX", "TD", "TDAC", "TDACU", "TDC", "TDF", "TDG",
                        "TDOC",
                        "TDS", "TDTH", "TDUP", "TDW", "TDY", "TE", "TEAF", "TEAM", "TECH", "TECK", "TECTP", "TECX",
                        "TEF",
                        "TEI", "TEL", "TELA", "TELO", "TEM", "TEN", "TENB", "TENX", "TEO", "TER", "TERN", "TEVA", "TEX",
                        "TFC", "TFII", "TFIN", "TFINP", "TFPM", "TFSL", "TFX", "TG", "TGB", "TGI", "TGL", "TGLS",
                        "TGNA",
                        "TGS", "TGT", "TGTX", "TH", "THAR", "THC", "THCH", "THFF", "THG", "THM", "THO", "THQ", "THR",
                        "THRD", "THRM", "THRY", "THS", "THTX", "THW", "TIC", "TIGO", "TIGR", "TIL", "TILE", "TIMB",
                        "TIPT",
                        "TIRX", "TISI", "TITN", "TIVC", "TIXT", "TJX", "TK", "TKC", "TKLF", "TKNO", "TKO", "TKR", "TLF",
                        "TLK", "TLN", "TLPH", "TLRY", "TLS", "TLSA", "TLSI", "TLSIW", "TLX", "TLYS", "TM", "TMC",
                        "TMCI",
                        "TMCWW", "TMDE", "TMDX", "TME", "TMHC", "TMO", "TMP", "TMQ", "TMUS", "TNC", "TNDM", "TNET",
                        "TNFA",
                        "TNGX", "TNK", "TNL", "TNMG", "TNON", "TNONW", "TNXP", "TNYA", "TOI", "TOIIW", "TOL", "TOMZ",
                        "TOON", "TOP", "TOPP", "TOPS", "TOPW", "TORO", "TOST", "TOUR", "TOVX", "TOWN", "TOYO", "TPB",
                        "TPC", "TPCS", "TPET", "TPG", "TPGXL", "TPH", "TPIC", "TPL", "TPR", "TPST", "TPTA", "TPVG",
                        "TR",
                        "TRAK", "TRAW", "TRC", "TRDA", "TREE", "TREX", "TRGP", "TRI", "TRIB", "TRIN", "TRINI", "TRINZ",
                        "TRIP", "TRMB", "TRMD", "TRMK", "TRML", "TRN", "TRNO", "TRNR", "TRNS", "TROO", "TROW", "TROX",
                        "TRP", "TRS", "TRSG", "TRST", "TRT", "TRTN", "TRTX", "TRU", "TRUE", "TRUG", "TRUP", "TRV",
                        "TRVG",
                        "TRVI", "TRX", "TS", "TSAT", "TSBK", "TSBX", "TSCO", "TSE", "TSEM", "TSHA", "TSI", "TSLA",
                        "TSLX",
                        "TSM", "TSN", "TSQ", "TSSI", "TSVT", "TT", "TTAM", "TTAN", "TTC", "TTD", "TTE", "TTEC", "TTEK",
                        "TTGT", "TTI", "TTMI", "TTNP", "TTSH", "TTWO", "TU", "TURB", "TURN", "TUSK", "TUYA", "TV",
                        "TVACU",
                        "TVC", "TVE", "TVGN", "TVGNW", "TVRD", "TVTX", "TW", "TWFG", "TWG", "TWI", "TWIN", "TWLO",
                        "TWN",
                        "TWNP", "TWO", "TWST", "TX", "TXG", "TXMD", "TXN", "TXNM", "TXO", "TXRH", "TXT", "TY", "TYG",
                        "TYGO", "TYL", "TYRA", "TZOO", "TZUP", "U", "UA", "UAA", "UAL", "UAMY", "UAN", "UAVS", "UBCP",
                        "UBER", "UBFO", "UBS", "UBSI", "UBX", "UBXG", "UCAR", "UCB", "UCL", "UCTT", "UDMY", "UDR", "UE",
                        "UEC", "UEIC", "UFCS", "UFG", "UFI", "UFPI", "UFPT", "UG", "UGI", "UGP", "UGRO", "UHAL", "UHG",
                        "UHS", "UHT", "UI", "UIS", "UK", "UKOMW", "UL", "ULBI", "ULCC", "ULH", "ULS", "ULTA", "ULY",
                        "UMAC", "UMBF", "UMBFP", "UMC", "UMH", "UNB", "UNCY", "UNF", "UNFI", "UNH", "UNIT", "UNM",
                        "UNMA",
                        "UNP", "UNTY", "UOKA", "UONE", "UONEK", "UP", "UPB", "UPBD", "UPC", "UPLD", "UPS", "UPST",
                        "UPWK",
                        "UPXI", "URBN", "URG", "URGN", "URI", "UROY", "USA", "USAC", "USAR", "USARW", "USAS", "USAU",
                        "USB", "USCB", "USEA", "USEG", "USFD", "USGO", "USGOW", "USIO", "USLM", "USM", "USNA", "USPH",
                        "UTF", "UTG", "UTHR", "UTI", "UTL", "UTMD", "UTSI", "UTZ", "UUU", "UUUU", "UVE", "UVSP", "UVV",
                        "UWMC", "UXIN", "UYSCU", "UZD", "UZE", "UZF", "V", "VABK", "VAC", "VACH", "VACHW", "VAL",
                        "VALE",
                        "VALN", "VALU", "VANI", "VATE", "VBF", "VBNK", "VBTX", "VC", "VCEL", "VCIC", "VCICU", "VCIG",
                        "VCSA", "VCTR", "VCV", "VCYT", "VECO", "VEEA", "VEEE", "VEEV", "VEL", "VENU", "VEON", "VERA",
                        "VERB", "VERI", "VERO", "VERU", "VERV", "VERX", "VET", "VFC", "VFF", "VFL", "VFS", "VFSWW",
                        "VG",
                        "VGAS", "VGASW", "VGI", "VGM", "VGZ", "VHC", "VHI", "VIASP", "VIAV", "VICI", "VICR", "VIGL",
                        "VIK",
                        "VINP", "VIOT", "VIPS", "VIR", "VIRC", "VIRT", "VIST", "VITL", "VIV", "VIVK", "VIVS", "VKI",
                        "VKQ",
                        "VKTX", "VLCN", "VLGEA", "VLN", "VLO", "VLRS", "VLT", "VLTO", "VLY", "VLYPN", "VLYPO", "VLYPP",
                        "VMAR", "VMC", "VMD", "VMEO", "VMI", "VMO", "VNCE", "VNDA", "VNET", "VNO", "VNOM", "VNRX",
                        "VNT",
                        "VOC", "VOD", "VOR", "VOXR", "VOYA", "VPG", "VPV", "VRA", "VRAR", "VRAX", "VRCA", "VRDN", "VRE",
                        "VREX", "VRM", "VRME", "VRMEW", "VRN", "VRNA", "VRNS", "VRNT", "VRRM", "VRSK", "VRSN", "VRT",
                        "VRTS", "VRTX", "VS", "VSA", "VSAT", "VSCO", "VSEC", "VSEE", "VSEEW", "VSH", "VSME", "VST",
                        "VSTA",
                        "VSTE", "VSTEW", "VSTM", "VSTS", "VTAK", "VTEX", "VTGN", "VTLE", "VTMX", "VTN", "VTOL", "VTR",
                        "VTRS", "VTS", "VTSI", "VTVT", "VTYX", "VUZI", "VVOS", "VVPR", "VVR", "VVV", "VVX", "VXRT",
                        "VYGR",
                        "VYNE", "VYX", "VZLA", "W", "WAB", "WABC", "WAFD", "WAFDP", "WAFU", "WAI", "WAL", "WALD",
                        "WASH",
                        "WAT", "WATT", "WAVE", "WAY", "WB", "WBA", "WBD", "WBS", "WBTN", "WBX", "WCC", "WCN", "WCT",
                        "WD",
                        "WDAY", "WDC", "WDFC", "WDH", "WDI", "WDS", "WEA", "WEAV", "WEC", "WELL", "WEN", "WERN", "WES",
                        "WEST", "WETH", "WETO", "WEX", "WEYS", "WF", "WFC", "WFCF", "WFF", "WFG", "WFRD", "WGO", "WGRX",
                        "WGS", "WGSWW", "WH", "WHD", "WHF", "WHFCL", "WHG", "WHLR", "WHLRD", "WHLRL", "WHLRP", "WHR",
                        "WHWK", "WIA", "WILC", "WIMI", "WINA", "WING", "WINT", "WIT", "WIW", "WIX", "WK", "WKC", "WKEY",
                        "WKHS", "WKSP", "WLAC", "WLDN", "WLDS", "WLDSW", "WLFC", "WLGS", "WLK", "WLKP", "WLY", "WLYB",
                        "WM", "WMB", "WMG", "WMK", "WMPN", "WMS", "WMT", "WNC", "WNEB", "WNS", "WNW", "WOK", "WOLF",
                        "WOOF", "WOR", "WORX", "WOW", "WPC", "WPM", "WPP", "WPRT", "WRAP", "WRB", "WRBY", "WRD", "WRLD",
                        "WRN", "WS", "WSBC", "WSBCP", "WSBF", "WSC", "WSFS", "WSM", "WSO", "WSR", "WST", "WT", "WTBA",
                        "WTF", "WTFC", "WTFCM", "WTFCP", "WTI", "WTM", "WTO", "WTRG", "WTS", "WTTR", "WTW", "WU",
                        "WULF",
                        "WVE", "WVVI", "WVVIP", "WW", "WWD", "WWR", "WWW", "WXM", "WY", "WYHG", "WYNN", "WYY", "X",
                        "XAGE",
                        "XAGEW", "XAIR", "XBIO", "XBIT", "XBP", "XCH", "XCUR", "XEL", "XELB", "XENE", "XERS", "XFLT",
                        "XFOR", "XGN", "XHG", "XHLD", "XHR", "XIFR", "XIN", "XLO", "XMTR", "XNCR", "XNET", "XOM",
                        "XOMA",
                        "XOMAO", "XOMAP", "XOS", "XP", "XPEL", "XPER", "XPEV", "XPL", "XPO", "XPOF", "XPON", "XPRO",
                        "XRAY", "XRTX", "XRX", "XTIA", "XTKG", "XTLB", "XTNT", "XWEL", "XXII", "XYF", "XYL", "XYLO",
                        "XYZ",
                        "Y", "YAAS", "YALA", "YCBD", "YELP", "YETI", "YEXT", "YGMZ", "YHC", "YHGJ", "YHNA", "YHNAR",
                        "YI",
                        "YIBO", "YJ", "YMAB", "YMM", "YORW", "YOSH", "YOTA", "YOTAR", "YOU", "YPF", "YQ", "YRD", "YSG",
                        "YSXT", "YTRA", "YUM", "YUMC", "YXT", "YYAI", "YYGH", "Z", "ZAPP", "ZAPPW", "ZBAI", "ZBAO",
                        "ZBH",
                        "ZBIO", "ZBRA", "ZCAR", "ZCARW", "ZCMD", "ZD", "ZDGE", "ZENA", "ZENV", "ZEO", "ZEOWW", "ZEPP",
                        "ZETA", "ZEUS", "ZG", "ZGN", "ZH", "ZI", "ZIM", "ZIMV", "ZION", "ZIONP", "ZIP", "ZJK", "ZJYL",
                        "ZK", "ZKH", "ZKIN", "ZLAB", "ZM", "ZNTL", "ZONE", "ZOOZ", "ZS", "ZSPC", "ZTEK", "ZTO", "ZTR",
                        "ZTS", "ZUMZ", "ZURA", "ZVIA", "ZVRA", "ZVSA", "ZWS", "ZYBT", "ZYME", "ZYXI",

                        # ETFs
                        "AADR", "AAPB", "AAPD", "AAPR", "AAPU", "AAPW", "AAPX", "AAPY", "AAXJ", "ABCS", "ABEQ", "ABFL",
                        "ABHY", "ABIG", "ABLD", "ABLG", "ABNY", "ABOT", "ACES", "ACGR", "ACLC", "ACSI", "ACTV", "ACVF",
                        "ACWI", "ACWX", "ADBG", "ADIV", "ADPV", "ADVE", "AESR", "AFK", "AFLG", "AFMC", "AFSC", "AFSM",
                        "AFTY", "AGEM", "AGIX", "AGMI", "AGNG", "AGQI", "AGRW", "AHLT", "AHOY", "AIA", "AIBD", "AIBU",
                        "AIDB", "AIEQ", "AIFD", "AIQ", "AIRL", "AIS", "AIVC", "AIVI", "AIVL", "AJAN", "AJUL", "ALAI",
                        "ALIL", "ALLW", "ALTL", "ALTY", "AMDD", "AMDG", "AMDL", "AMDS", "AMDY", "AMID", "AMJ", "AMLP",
                        "AMNA", "AMND", "AMOM", "AMTR", "AMUB", "AMUU", "AMZA", "AMZD", "AMZP", "AMZU", "AMZY", "AMZZ",
                        "ANEW", "AOCT", "AOTG", "APED", "APIE", "APLY", "APOC", "APPX", "APRD", "APRH", "APRJ", "APRP",
                        "APRQ", "APRT", "APRW", "APRZ", "APUE", "AQWA", "ARB", "AREA", "ARGT", "ARKF", "ARKW", "ARKX",
                        "ARLU", "ARMG", "ARMH", "ARMR", "ARTY", "ARVR", "ASEA", "ASIA", "ASLV", "ASMG", "ASMH", "ATFV",
                        "AUGP", "AUGT", "AUGW", "AUGZ", "AUMI", "AUSF", "AVDE", "AVDS", "AVDV", "AVEE", "AVEM", "AVES",
                        "AVGE", "AVGG", "AVGV", "AVGX", "AVIE", "AVIV", "AVL", "AVLC", "AVLV", "AVMA", "AVMC", "AVMV",
                        "AVNM", "AVNV", "AVS", "AVSC", "AVSD", "AVSE", "AVSU", "AVUQ", "AVUS", "AVUV", "AVXC", "AWAY",
                        "AWEG", "AZNH", "AZTD", "BABO", "BABX", "BAFE", "BAI", "BALI", "BALT", "BAMD", "BAMG", "BAMU",
                        "BAMV", "BAPR", "BATT", "BAUG", "BBAX", "BBCA", "BBEM", "BBEU", "BBH", "BBIB", "BBIN", "BBIP",
                        "BBJP", "BBLU", "BBMC", "BBRE", "BBSA", "BBSC", "BBUS", "BCDF", "BCHI", "BCIL", "BCOR", "BCUS",
                        "BDCX", "BDEC", "BDGS", "BDIV", "BDRY", "BDVG", "BECO", "BEDZ", "BEEZ", "BELT", "BENJ", "BERZ",
                        "BETZ", "BFEB", "BFIT", "BFRE", "BFRZ", "BGDV", "BGIG", "BGRO", "BIB", "BIBL", "BIDD", "BIGB",
                        "BIGY", "BILD", "BINV", "BIS", "BITQ", "BIZD", "BJAN", "BJK", "BJUL", "BJUN", "BKCG", "BKCH",
                        "BKCI", "BKDV", "BKEM", "BKES", "BKF", "BKGI", "BKIE", "BKIS", "BKIV", "BKLC", "BKMC", "BKSE",
                        "BKUS", "BKWO", "BLCN", "BLCR", "BLCV", "BLDG", "BLES", "BLLD", "BLOK", "BMAR", "BMAX", "BMAY",
                        "BMED", "BMVP", "BNE", "BNGE", "BNKD", "BNKU", "BNOV", "BOAT", "BOBP", "BOCT", "BOED", "BOEU",
                        "BOTT", "BOTZ", "BOUT", "BPAY", "BPH", "BRAZ", "BRF", "BRHY", "BRIF", "BRKD", "BRKU", "BRNY",
                        "BSEP", "BSMC", "BSR", "BSTP", "BSVO", "BTAL", "BTEC", "BTEK", "BTR", "BUFB", "BUFC", "BUFD",
                        "BUFF", "BUFG", "BUFI", "BUFM", "BUFP", "BUFR", "BUFS", "BUFT", "BUFZ", "BUG", "BUL", "BULD",
                        "BULZ", "BUSA", "BUYO", "BUYW", "BUYZ", "BUZZ", "BWEB", "BWTG", "BYOB", "BYTE", "BZQ", "CACG",
                        "CAFG", "CAML", "CAMX", "CANC", "CARD", "CARK", "CARU", "CARZ", "CAS", "CATH", "CBLS", "CBSE",
                        "CCMG", "CCNR", "CCOR", "CCSO", "CDEI", "CEFA", "CEPI", "CFCV", "CGBL", "CGCV", "CGDG", "CGDV",
                        "CGGE", "CGGO", "CGGR", "CGIC", "CGIE", "CGMM", "CGNG", "CGRO", "CGUS", "CGV", "CGW", "CGXU",
                        "CHAT", "CHB", "CHGX", "CHIC", "CHIE", "CHIH", "CHII", "CHIK", "CHIM", "CHIQ", "CHIR", "CHIS",
                        "CHIU", "CHIX", "CHPS", "CHPY", "CIRC", "CLDL", "CLIA", "CLIX", "CLNR", "CLOD", "CLOU", "CLRG",
                        "CLSA", "CLSC", "CLSE", "CLSM", "CNBS", "CNCR", "CNEQ", "CNRG", "CNYA", "COAL", "COIG", "COIW",
                        "CONI", "CONL", "CONY", "COPJ", "COPP", "COPX", "COPY", "CORO", "COWG", "COWS", "CPAI", "CPNJ",
                        "CPNM", "CPNQ", "CPNS", "CPRA", "CPRJ", "CPRO", "CPRY", "CPSA", "CPSD", "CPSF", "CPSJ", "CPSM",
                        "CPSN", "CPSO", "CPSP", "CPSR", "CPST", "CPSY", "CQQQ", "CRAK", "CRIT", "CRMG", "CRPT", "CRSH",
                        "CRTC", "CRUZ", "CRWL", "CSD", "CSM", "CSMD", "CSNR", "CSPF", "CSRE", "CTA", "CTEC", "CTEX",
                        "CURE", "CUT", "CVAR", "CVIE", "CVLC", "CVMC", "CVNX", "CVNY", "CVRD", "CVSE", "CVY", "CWEB",
                        "CWI", "CWS", "CZA", "CZAR", "DABS", "DALI", "DAPP", "DAPR", "DARP", "DAT", "DAUG", "DAX",
                        "DBEF", "DBEM", "DBJA", "DBJP", "DBMF", "DCOR", "DDEC", "DDIV", "DDM", "DECO", "DECP", "DECT",
                        "DECW", "DECZ", "DEEP", "DEHP", "DEIF", "DEM", "DEMZ", "DES", "DESK", "DEW", "DEXC", "DFAC",
                        "DFAE", "DFAI", "DFAS", "DFAT", "DFAU", "DFAW", "DFAX", "DFE", "DFEB", "DFEM", "DFEN", "DFEV",
                        "DFGR", "DFHY", "DFIS", "DFIV", "DFJ", "DFLV", "DFNL", "DFNV", "DFRA", "DFSE", "DFSI", "DFSU",
                        "DFSV", "DFUS", "DFUV", "DFVE", "DFVX", "DGIN", "DGS", "DGT", "DHS", "DHSB", "DIA", "DIEM",
                        "DIG", "DIHP", "DIM", "DINT", "DIP", "DIPS", "DISO", "DISV", "DIV", "DIVB", "DIVD", "DIVG",
                        "DIVI", "DIVL", "DIVO", "DIVP", "DIVS", "DIVY", "DIVZ", "DJAN", "DJIA", "DJUL", "DJUN", "DKRB",
                        "DLLL", "DLN", "DLS", "DMAR", "DMAT", "DMAY", "DMCY", "DMDV", "DMXF", "DNL", "DNOV", "DOCT",
                        "DOG", "DOL", "DON", "DPST", "DRAG", "DRAI", "DRIV", "DRLL", "DRN", "DRUP", "DRV", "DSEP",
                        "DSI", "DSJA", "DSMC", "DSPY", "DSTL", "DSTX", "DTAN", "DTCR", "DTD", "DTEC", "DTH", "DTRE",
                        "DUBS", "DUG", "DUHP", "DUKH", "DUKQ", "DUKX", "DUKZ", "DULL", "DURA", "DUSA", "DUSL", "DUST",
                        "DVAL", "DVDN", "DVLU", "DVND", "DVOL", "DVQQ", "DVSP", "DVY", "DVYA", "DVYE", "DWAS", "DWAW",
                        "DWCR", "DWLD", "DWM", "DWMF", "DWSH", "DWX", "DXD", "DXIV", "DXJ", "DXJS", "DXUV", "DYLG",
                        "DYNF", "DYNI", "DYTA", "EAFG", "EAGL", "EALT", "EAPR", "EATV", "EATZ", "EBI", "EBIT", "EBIZ",
                        "EBUF", "ECH", "ECLN", "ECML", "ECNS", "ECON", "ECOW", "EDC", "EDEN", "EDGH", "EDGI", "EDGU",
                        "EDIV", "EDOW", "EDZ", "EELV", "EEM", "EEMD", "EEMX", "EES", "EET", "EEV", "EFA", "EFAA",
                        "EFAS", "EFAV", "EFAX", "EFFE", "EFFI", "EFG", "EFIV", "EFNL", "EFO", "EFRA", "EFU", "EFV",
                        "EFZ", "EGGQ", "EGGS", "EGGY", "EGLE", "EGPT", "EGUS", "EIDO", "EINC", "EIPI", "EIPX", "EIRL",
                        "EIS", "EJAN", "EJUL", "EKG", "ELCV", "ELFY", "ELIL", "ELIS", "ELON", "EMC", "EMCC", "EMCR",
                        "EMCS", "EMDM", "EMEQ", "EMES", "EMFM", "EMFQ", "EMGF", "EMIF", "EMLP", "EMM", "EMMF", "EMOT",
                        "EMPB", "EMQQ", "EMSF", "EMTY", "EMXC", "EMXF", "ENDW", "ENOR", "ENRG", "ENZL", "EOCT", "EPHE",
                        "EPI", "EPMB", "EPMV", "EPOL", "EPP", "EPS", "EPSB", "EPSV", "EPU", "EPV", "EQIN", "EQL",
                        "EQLS", "EQRR", "EQTY", "EQUL", "ERET", "ERNZ", "ERSX", "ERTH", "ERX", "ERY", "ESG", "ESGD",
                        "ESGE", "ESGG", "ESGU", "ESGV", "ESIX", "ESML", "ESMV", "ESPO", "ESUS", "ETEC", "ETHO", "ETQ",
                        "ETU", "EUDG", "EUFN", "EUM", "EUSA", "EUSC", "EUSM", "EV", "EVAV", "EVUS", "EVX", "EVXX",
                        "EWA", "EWC", "EWD", "EWG", "EWH", "EWI", "EWJ", "EWJV", "EWK", "EWL", "EWM", "EWN", "EWO",
                        "EWP", "EWQ", "EWS", "EWT", "EWU", "EWUS", "EWV", "EWW", "EWX", "EWY", "EWZ", "EWZS", "EXI",
                        "EYLD", "EZA", "EZJ", "EZM", "EZU", "FAB", "FAD", "FAI", "FAIL", "FALN", "FAN", "FAPR", "FARX",
                        "FAS", "FAUG", "FAZ", "FBCG", "FBCV", "FBL", "FBOT", "FBT", "FBUF", "FBY", "FBZ", "FCA", "FCFY",
                        "FCG", "FCLD", "FCOM", "FCPI", "FCTE", "FCTR", "FCUS", "FDCE", "FDCF", "FDD", "FDEC", "FDEM",
                        "FDEV", "FDFF", "FDG", "FDGR", "FDHT", "FDIF", "FDIG", "FDIS", "FDIV", "FDL", "FDLO", "FDLS",
                        "FDM", "FDMO", "FDN", "FDND", "FDNI", "FDRR", "FDRV", "FDT", "FDTB", "FDTS", "FDTX", "FDV",
                        "FDVL", "FDVV", "FDWM", "FEAC", "FEAT", "FEBP", "FEBT", "FEBW", "FEBZ", "FEDL", "FEEM", "FEGE",
                        "FEIG", "FELC", "FELG", "FELV", "FEM", "FEMR", "FEMS", "FENI", "FENY", "FEOE", "FEP", "FEPI",
                        "FESM", "FEUS", "FEX", "FEZ", "FFEB", "FFLC", "FFLG", "FFLV", "FFND", "FFOG", "FFSM", "FFTY",
                        "FGD", "FGM", "FGSM", "FHEQ", "FHLC", "FIAT", "FICS", "FIDI", "FIDU", "FILL", "FINE", "FINT",
                        "FINX", "FIRI", "FIRS", "FITE", "FIVA", "FIVY", "FIW", "FIXP", "FIXT", "FJAN", "FJP", "FJUL",
                        "FJUN", "FKU", "FLAG", "FLAO", "FLAU", "FLAX", "FLBR", "FLCA", "FLCC", "FLCE", "FLCG", "FLCH",
                        "FLCV", "FLDZ", "FLEE", "FLEU", "FLGB", "FLGR", "FLHK", "FLIN", "FLJH", "FLJJ", "FLJP", "FLKR",
                        "FLLA", "FLMX", "FLN", "FLOT", "FLOW", "FLQL", "FLQM", "FLQS", "FLRG", "FLSA", "FLSW", "FLTW",
                        "FLV", "FLXR", "FLYD", "FLYU", "FMAG", "FMAR", "FMAT", "FMAY", "FMCE", "FMCX", "FMDE", "FMED",
                        "FMET", "FMQQ", "FMTM", "FMUB", "FMUN", "FNCL", "FNGA", "FNGB", "FNGD", "FNGG", "FNGO", "FNGS",
                        "FNK", "FNOV", "FNX", "FNY", "FOCT", "FORH", "FOVL", "FPA", "FPRO", "FPX", "FPXE", "FQAL",
                        "FRDM", "FREL", "FRI", "FRNW", "FRTY", "FSCC", "FSCS", "FSEP", "FSGS", "FSMD", "FSST", "FSTA",
                        "FSZ", "FTA", "FTAG", "FTC", "FTCB", "FTCE", "FTDS", "FTEC", "FTGS", "FTHF", "FTHI", "FTIF",
                        "FTKI", "FTLS", "FTQI", "FTRI", "FTWO", "FTXG", "FTXH", "FTXL", "FTXN", "FTXO", "FTXR", "FUNL",
                        "FUSI", "FUTY", "FVAL", "FVD", "FWD", "FXD", "FXG", "FXH", "FXI", "FXL", "FXN", "FXO", "FXP",
                        "FXR", "FXU", "FXZ", "FYC", "FYEE", "FYLG", "FYT", "FYX", "GABF", "GAMR", "GAPR", "GARP",
                        "GAST", "GAUG", "GBLD", "GBUG", "GBUY", "GCAD", "GCLN", "GDEC", "GDEF", "GDIV", "GDOC", "GDVD",
                        "GDX", "GDXD", "GDXJ", "GDXU", "GDXY", "GEM", "GEME", "GEND", "GENW", "GERM", "GFEB", "GFGF",
                        "GFLW", "GFOF", "GGLL", "GGLS", "GGM", "GGME", "GGRW", "GGUS", "GHEE", "GIAX", "GII", "GIND",
                        "GINN", "GINX", "GJAN", "GJUL", "GJUN", "GK", "GLCR", "GLDB", "GLDY", "GLIF", "GLIN", "GLOF",
                        "GLOV", "GLOW", "GLRY", "GMAR", "GMAY", "GMET", "GMF", "GMMA", "GMOI", "GMOV", "GNOM", "GNOV",
                        "GNR", "GOAU", "GOCT", "GOEX", "GOOP", "GOOX", "GOOY", "GOP", "GPAL", "GPIQ", "GPIX", "GPOW",
                        "GPTY", "GQI", "GQQQ", "GREI", "GREK", "GRES", "GRID", "GRNY", "GRPZ", "GRW", "GSC", "GSEE",
                        "GSEP", "GSEU", "GSEW", "GSFP", "GSIB", "GSID", "GSIE", "GSJY", "GSKH", "GSLC", "GSPY", "GSSC",
                        "GSUS", "GTEK", "GTR", "GUNR", "GURU", "GUSA", "GUSH", "GVIP", "GVLU", "GVUS", "GWX", "GXC",
                        "GXDW", "GXG", "GXUS", "HACK", "HAIL", "HAP", "HAPI", "HAPR", "HAPS", "HAPY", "HART", "HAUS",
                        "HAUZ", "HBTA", "HCMT", "HCOW", "HDEF", "HDGE", "HDLB", "HDMV", "HDRO", "HDUS", "HEAL", "HEAT",
                        "HECO", "HEDJ", "HEGD", "HEJD", "HELO", "HELX", "HEQQ", "HEQT", "HERD", "HERO", "HFGO", "HFSP",
                        "HFXI", "HIBL", "HIBS", "HIDV", "HIMZ", "HIPS", "HISF", "HJAN", "HJEN", "HJUL", "HKND", "HLAL",
                        "HLGE", "HOCT", "HOMZ", "HOOG", "HOOX", "HOOY", "HQGO", "HRTS", "HSBH", "HSCZ", "HSMV", "HTEC",
                        "HTUS", "HUSV", "HVAC", "HWAY", "HWSM", "HYBI", "HYDR", "HYLG", "IAI", "IAK", "IAPR", "IAT",
                        "IAUG", "IBAT", "IBB", "IBBQ", "IBLC", "IBOT", "IBRN", "IBUF", "IBUY", "ICAP", "ICF", "ICLN",
                        "ICOI", "ICOP", "IDAT", "IDEC", "IDEF", "IDEV", "IDGT", "IDHQ", "IDLV", "IDNA", "IDRV", "IDU",
                        "IDUB", "IDV", "IDVO", "IDX", "IEDI", "IEO", "IEQ", "IETC", "IEV", "IEZ", "IFEB", "IFED",
                        "IFGL", "IFRA", "IGE", "IGF", "IGM", "IGPT", "IGRO", "IGTR", "IGV", "IHAK", "IHE", "IHF", "IHI",
                        "IJAN", "IJH", "IJJ", "IJK", "IJR", "IJS", "IJT", "IJUL", "IJUN", "ILCB", "ILCG", "ILCV",
                        "ILDR", "ILF", "ILIT", "ILOW", "IMAR", "IMAY", "IMCB", "IMCG", "IMCV", "IMRA", "IMST", "INAV",
                        "INC", "INCE", "INCO", "INDA", "INDE", "INDF", "INDH", "INDL", "INDY", "INEQ", "INFL", "INFO",
                        "INFR", "INNO", "INOV", "INQQ", "INRO", "INTF", "INTW", "INVN", "IOCT", "ION", "IONL", "IONX",
                        "IOO", "IOPP", "IPAY", "IPDP", "IPPP", "IQDE", "IQDF", "IQDY", "IQIN", "IQM", "IQQQ", "IQRA",
                        "IQSI", "IQSM", "IQSU", "IRBA", "IRET", "ISCB", "ISCF", "ISCG", "ISCV", "ISEP", "ISHP", "ISMD",
                        "ISVL", "ISZE", "ITA", "ITAN", "ITB", "ITEQ", "ITOT", "IUS", "IUSG", "IUSV", "IVE", "IVEG",
                        "IVLU", "IVOG", "IVOO", "IVOV", "IVRA", "IVRS", "IVV", "IVVB", "IVVW", "IVW", "IWB", "IWC",
                        "IWD", "IWDL", "IWF", "IWFG", "IWFH", "IWFL", "IWIN", "IWL", "IWLG", "IWM", "IWMI", "IWML",
                        "IWMW", "IWMY", "IWN", "IWO", "IWP", "IWR", "IWS", "IWTR", "IWV", "IWX", "IWY", "IXC", "IXG",
                        "IXJ", "IXN", "IXP", "IYC", "IYE", "IYF", "IYG", "IYH", "IYJ", "IYK", "IYM", "IYR", "IYT",
                        "IYW", "IYY", "IYZ", "IZRL", "JADE", "JAJL", "JAND", "JANH", "JANJ", "JANP", "JANQ", "JANT",
                        "JANU", "JANW", "JANZ", "JAPN", "JAVA", "JCHI", "JCTR", "JDIV", "JDOC", "JDVI", "JEMA", "JEPI",
                        "JETD", "JETS", "JETU", "JFWD", "JGLO", "JGRO", "JGRW", "JHAC", "JHDV", "JHEM", "JHID", "JHMD",
                        "JHML", "JHMM", "JHSC", "JIG", "JIRE", "JIVE", "JMEE", "JMID", "JMOM", "JNEU", "JOET", "JPAN",
                        "JPEF", "JPEM", "JPME", "JPMO", "JPSE", "JPSV", "JPXN", "JPY", "JQUA", "JRNY", "JSMD", "JSML",
                        "JSTC", "JULD", "JULH", "JULJ", "JULP", "JULQ", "JULT", "JULU", "JULW", "JULZ", "JUNM", "JUNP",
                        "JUNT", "JUNW", "JUNZ", "JUSA", "JUST", "JVAL", "JXI", "KALL", "KAPR", "KARS", "KAUG", "KBAB",
                        "KBE", "KBUF", "KBUY", "KBWD", "KBWP", "KBWY", "KCAI", "KCAL", "KCE", "KDEC", "KDEF", "KDIV",
                        "KEAT", "KEM", "KEMQ", "KEMX", "KFEB", "KFVG", "KGRN", "KGRO", "KIE", "KJAN", "KJUL", "KJUN",
                        "KLDW", "KLIP", "KLMN", "KLMT", "KLNE", "KLXY", "KMAR", "KMAY", "KMID", "KNCT", "KNG", "KNGS",
                        "KNGZ", "KNO", "KNOV", "KNOW", "KOCG", "KOCT", "KOIN", "KOKU", "KOMP", "KONG", "KOOL", "KPDD",
                        "KPOP", "KPRO", "KQQQ", "KRBN", "KRE", "KRMA", "KROP", "KSA", "KSEA", "KSEP", "KSPY", "KSTR",
                        "KTEC", "KURE", "KVLE", "KWT", "KXI", "LAPR", "LAYS", "LBAY", "LBO", "LCDL", "LCDS", "LCF",
                        "LCG", "LCLG", "LCTD", "LCTU", "LDEM", "LDRX", "LEAD", "LEGR", "LFEQ", "LFGY", "LFSC", "LGCF",
                        "LGDX", "LGHT", "LGLZ", "LGRO", "LIT", "LITL", "LITP", "LIVR", "LJAN", "LJUL", "LLYX", "LMBO",
                        "LNGG", "LNGZ", "LOCT", "LOGO", "LOPP", "LOUP", "LOWV", "LPRE", "LQAI", "LRGC", "LRGE", "LRGF",
                        "LRGG", "LRND", "LRNZ", "LSAF", "LSEQ", "LSGR", "LST", "LSVD", "LTL", "LUX", "LUXX", "LVHD",
                        "LVHI", "LVOL", "LYLD", "MADE", "MAGA", "MAGQ", "MAGS", "MAGX", "MAGY", "MAKX", "MAMB", "MARB",
                        "MARM", "MARO", "MART", "MARW", "MARZ", "MAVF", "MAXI", "MAYP", "MAYT", "MAYU", "MAYW", "MBCC",
                        "MBOX", "MCDS", "MCH", "MCHI", "MCHS", "MCSE", "MDCP", "MDEV", "MDPL", "MDY", "MDYG", "MDYV",
                        "MEDI", "MEDX", "MEM", "MEME", "MEMS", "MEMX", "METD", "METU", "METV", "MEXX", "MFDX", "MFEM",
                        "MFUS", "MGC", "MGK", "MGMT", "MGNR", "MGRO", "MGV", "MID", "MIDE", "MIDU", "MILN", "MINV",
                        "MISL", "MJ", "MJUS", "MKAM", "MKOR", "MLPA", "MLPD", "MLPR", "MLPX", "MMLG", "MMSC", "MMTM",
                        "MNRS", "MNTL", "MOAT", "MODL", "MOHR", "MOO", "MOON", "MOTE", "MOTG", "MOTI", "MOTO", "MPRO",
                        "MQQQ", "MRAD", "MRAL", "MRCP", "MRND", "MRNY", "MSFD", "MSFL", "MSFO", "MSFU", "MSFX", "MSFY",
                        "MSLC", "MSOS", "MSOX", "MSSM", "MSSS", "MST", "MSTQ", "MSTU", "MSTX", "MSTZ", "MSVX", "MTUL",
                        "MUD", "MULL", "MUSQ", "MUU", "MVAL", "MVLL", "MVPA", "MVPL", "MVPS", "MVRL", "MVV", "MXI",
                        "MYLD", "MYY", "MZZ", "NACP", "NAIL", "NANC", "NAPR", "NATO", "NAUG", "NBCC", "NBCE", "NBCR",
                        "NBDS", "NBET", "NBGR", "NBGX", "NBJP", "NBOS", "NBSM", "NDEC", "NDIA", "NDIV", "NDJI", "NDVG",
                        "NERD", "NEWZ", "NFEB", "NFLP", "NFLU", "NFLY", "NFRA", "NFTY", "NFXL", "NFXS", "NGE", "NIKL",
                        "NITE", "NIXT", "NJAN", "NJUL", "NJUN", "NLR", "NMAR", "NMAY", "NNOV", "NOCT", "NORW", "NOVP",
                        "NOVZ", "NRES", "NRGD", "NRGU", "NRSH", "NSCR", "NSCS", "NSEP", "NSI", "NSPI", "NTKI", "NTZG",
                        "NUDM", "NUDV", "NUEM", "NUGO", "NUGT", "NUKZ", "NULC", "NULG", "NULV", "NUMG", "NUMV", "NURE",
                        "NUSC", "NVBT", "NVBW", "NVD", "NVDD", "NVDG", "NVDL", "NVDQ", "NVDS", "NVDU", "NVDW", "NVDX",
                        "NVDY", "NVIR", "NVOH", "NVOX", "NVQ", "NVW", "NVYY", "NWLG", "NXTE", "NXTG", "NXTI", "NXTV",
                        "NZUS", "OAEM", "OAIA", "OAIE", "OAIM", "OAKM", "OALC", "OARK", "OASC", "OBOR", "OCEN", "OCFS",
                        "OCTA", "OCTD", "OCTH", "OCTJ", "OCTP", "OCTQ", "OCTT", "OCTW", "OCTZ", "ODDS", "OEF", "OEUR",
                        "OFOS", "OGIG", "OGSP", "OIH", "OILD", "OILT", "OILU", "OMAH", "OMFL", "OMFS", "OND", "ONEQ",
                        "ONLN", "OOSP", "OOTO", "OPPX", "OPTZ", "ORCX", "ORR", "OSCV", "OSEA", "OUSA", "OUSM", "OVL",
                        "OVLH", "OVS", "OWNB", "OZEM", "PAAA", "PABD", "PABU", "PAK", "PALC", "PALD", "PALU", "PAMC",
                        "PANG", "PAPR", "PATN", "PAUG", "PAVE", "PAWZ", "PBAP", "PBAU", "PBD", "PBDC", "PBDE", "PBE",
                        "PBFB", "PBFR", "PBJ", "PBJA", "PBJL", "PBJN", "PBMR", "PBMY", "PBNV", "PBOC", "PBP", "PBQQ",
                        "PBSE", "PBUS", "PBW", "PCCE", "PCEM", "PCGG", "PCIG", "PDEC", "PDN", "PDP", "PEJ", "PEMX",
                        "PEPS", "PEVC", "PEXL", "PEY", "PEZ", "PFEB", "PFFD", "PFFR", "PFI", "PFM", "PFUT", "PFXF",
                        "PGAL", "PGF", "PGJ", "PGRO", "PHEQ", "PHO", "PICK", "PID", "PIE", "PILL", "PIN", "PINK", "PIO",
                        "PIZ", "PJAN", "PJBF", "PJFG", "PJFM", "PJFV", "PJIO", "PJP", "PJUL", "PJUN", "PKB", "PKW",
                        "PLDR", "PLTD", "PLTG", "PLTU", "PLTW", "PLTY", "PMAR", "PMAY", "PNOV", "PNQI", "POCT", "POTX",
                        "POWA", "PP", "PPA", "PPEM", "PPH", "PPIE", "PQAP", "PQDI", "PQJA", "PQJL", "PQOC", "PRAE",
                        "PRAY", "PREF", "PRF", "PRFZ", "PRMN", "PRN", "PRNT", "PRXG", "PRXV", "PSC", "PSCC", "PSCD",
                        "PSCE", "PSCF", "PSCH", "PSCI", "PSCJ", "PSCM", "PSCQ", "PSCT", "PSCU", "PSCW", "PSCX",
                        "PSDM", "PSEP", "PSET", "PSFD", "PSFF", "PSFJ", "PSFM", "PSFO", "PSI", "PSIL", "PSL", "PSMD",
                        "PSMJ", "PSMO", "PSMR", "PSP", "PSQ", "PSR", "PSTP", "PSTR", "PSWD", "PTEC", "PTEU", "PTF",
                        "PTH", "PTIR", "PTL", "PTLC", "PTMC", "PTNQ", "PUI", "PVAL", "PWB", "PWER", "PWRD", "PWV",
                        "PXE", "PXF", "PXH", "PXI", "PXJ", "PY", "PYPG", "PYPY", "PYZ", "QABA", "QARP", "QBER", "QBIG",
                        "QBUF", "QBUL", "QCAP", "QCJL", "QCLN", "QCLR", "QCML", "QDCC", "QDEC", "QDEF", "QDF", "QDIV",
                        "QDPL", "QDTE", "QDTY", "QDVO", "QDWN", "QFLR", "QGRO", "QGRW", "QHDG", "QID", "QIDX", "QINT",
                        "QLC", "QLD", "QLTI", "QLTY", "QLV", "QLVD", "QLVE", "QMAR", "QMID", "QMMY", "QNXT", "QOWZ",
                        "QQEW", "QQHG", "QQJG", "QQLV", "QQMG", "QQQ", "QQQA", "QQQD", "QQQE", "QQQG", "QQQI", "QQQJ",
                        "QQQM", "QQQN", "QQQS", "QQQT", "QQQU", "QQQW", "QQWZ", "QQXT", "QRFT", "QRMI", "QSIX", "QSML",
                        "QSPT", "QSWN", "QTAP", "QTEC", "QTJA", "QTJL", "QTOC", "QTOP", "QTR", "QTUM", "QULL", "QUP",
                        "QUSA", "QUVU", "QVML", "QVMM", "QVMS", "QXQ", "QYLD", "QYLG", "RAA", "RAFE", "RAYC", "RAYD",
                        "RAYE", "RAYJ", "RAYS", "RBLD", "RBUF", "RCGE", "RDIV", "RDOG", "RDTE", "RDTL", "RDTY", "RDVI",
                        "RDVY", "REAI", "RECS", "REGL", "REKT", "REM", "REMX", "RESE", "RESP", "RETL", "REVS", "REW",
                        "REZ", "RFDA", "RFDI", "RFEU", "RFFC", "RFG", "RFLR", "RFV", "RGEF", "RGTX", "RHRX", "RIFR",
                        "RILA", "RING", "RINT", "RIOX", "RJMG", "RKLX", "RLY", "RND", "RNEM", "RNEW", "RNIN", "RNRG",
                        "RNTY", "RNWZ", "ROAM", "ROBO", "ROBT", "RODE", "RODM", "ROE", "ROIS", "ROKT", "ROM", "ROMO",
                        "ROOF", "ROPE", "ROSC", "ROUS", "ROYA", "RPG", "RPHS", "RPV", "RSDE", "RSHO", "RSJN", "RSMC",
                        "RSMR", "RSMV", "RSP", "RSPA", "RSPD", "RSPE", "RSPF", "RSPG", "RSPH", "RSPM", "RSPN", "RSPS",
                        "RSPT", "RSSB", "RSSE", "RSSL", "RSSY", "RTAI", "RTH", "RUFF", "RUNN", "RUSC", "RVER", "RVNL",
                        "RVRB", "RWJ", "RWK", "RWL", "RWM", "RWO", "RWR", "RWX", "RXD", "RXI", "RXL", "RYLG", "RZG",
                        "RZV", "SAA", "SAEF", "SAGP", "SAMM", "SAMT", "SANE", "SAPH", "SARK", "SATO", "SAUG", "SAWG",
                        "SAWS", "SBB", "SCAP", "SCC", "SCDL", "SCDS", "SCDV", "SCHA", "SCHB", "SCHC", "SCHD", "SCHE",
                        "SCHF", "SCHG", "SCHH", "SCHK", "SCHM", "SCHV", "SCHX", "SCHY", "SCJ", "SCLZ", "SCMB", "SCY",
                        "SCZ", "SDD", "SDEM", "SDFI", "SDG", "SDIV", "SDOG", "SDP", "SDS", "SDSI", "SDTY", "SDVD",
                        "SDVY", "SDY", "SEA", "SECT", "SEEM", "SEF", "SEIE", "SEIM", "SEIQ", "SEIS", "SEIV", "SELV",
                        "SEMG", "SEMI", "SEPP", "SEPT", "SEPW", "SEPZ", "SETM", "SFEB", "SFLO", "SFLR", "SFY", "SFYF",
                        "SFYX", "SGLC", "SH", "SHDG", "SHEH", "SHLD", "SHNY", "SHOC", "SHPP", "SHRT", "SHRY", "SHUS",
                        "SIFI", "SIJ", "SIL", "SILJ", "SIMS", "SIXA", "SIXD", "SIXF", "SIXG", "SIXH", "SIXJ", "SIXL",
                        "SIXO", "SIXP", "SIXS", "SIXZ", "SJIM", "SKF", "SKRE", "SKYU", "SKYY", "SLVP", "SLX", "SLYG",
                        "SLYV", "SMAP", "SMAY", "SMCF", "SMCL", "SMCO", "SMCP", "SMCX", "SMCY", "SMCZ", "SMDX", "SMDY",
                        "SMH", "SMHX", "SMIG", "SMIN", "SMIZ", "SMLE", "SMLF", "SMLL", "SMMD", "SMMV", "SMN", "SMOG",
                        "SMOT", "SMRI", "SMST", "SMTH", "SNAV", "SNOV", "SNOY", "SNPD", "SNPE", "SNPG", "SNPV", "SNSR",
                        "SNTH", "SOCL", "SOFR", "SOFX", "SOLR", "SOLT", "SOLZ", "SOVF", "SOXL", "SOXM", "SOXQ", "SOXS",
                        "SOXW", "SOXX", "SOXY", "SPAM", "SPAQ", "SPAX", "SPBC", "SPBW", "SPBX", "SPC", "SPCX", "SPCY",
                        "SPCZ", "SPD", "SPDG", "SPDN", "SPDV", "SPDW", "SPEM", "SPEU", "SPFF", "SPGM", "SPHB", "SPHD",
                        "SPHQ", "SPLG", "SPMD", "SPMV", "SPQ", "SPRE", "SPRX", "SPSK", "SPTE", "SPTM", "SPUC", "SPUS",
                        "SPUT", "SPVM", "SPWO", "SPXE", "SPXL", "SPXS", "SPXU", "SPY", "SPYB", "SPYC", "SPYG", "SPYM",
                        "SPYT", "SPYV", "SQEW", "SQLV", "SQQQ", "SRET", "SRHQ", "SRHR", "SROI", "SRS", "SSG", "SSLY",
                        "SSO", "SSPX", "SSPY", "SSUS", "SSXU", "STCE", "STGF", "STHH", "STNC", "STRV", "STSB", "STXD",
                        "STXE", "STXG", "STXI", "STXK", "STXM", "STXV", "SUPL", "SUPP", "SURE", "SUSA", "SUSL", "SVAL",
                        "SVIX", "SVOL", "SXQG", "SXUS", "SYFI", "SYII", "SYNB", "SYUS", "SZK", "SZNE", "TACK", "TAFL",
                        "TAN", "TAPR", "TARK", "TAX", "TBG", "TBLU", "TCAF", "TCAL", "TCHI", "TCHP", "TDI", "TDIV",
                        "TDV", "TDVG", "TDVI", "TEC", "TECB", "TECL", "TECS", "TEK", "TEKX", "TEKY", "TEMP", "TEQI",
                        "TESL", "TGLR", "TGRT", "TGRW", "THCX", "THD", "THEQ", "THLV", "THMZ", "THNQ", "THNR", "THRO",
                        "TILT", "TIME", "TINT", "TINY", "TJAN", "TJUL", "TLCI", "TLTD", "TLTE", "TMAT", "TMDV", "TMET",
                        "TMFC", "TMFE", "TMFG", "TMFM", "TMFS", "TMFX", "TMH", "TMSL", "TNA", "TOAK", "TOGA", "TOK",
                        "TOKE", "TOLL", "TOPC", "TOPT", "TOUS", "TOV", "TPHD", "TPHE", "TPIF", "TPLC", "TPLE", "TPOR",
                        "TPSC", "TPYP", "TPZ", "TQQQ", "TQQY", "TRFK", "TRFM", "TRPL", "TSDD", "TSEL", "TSJA", "TSL",
                        "TSLG", "TSLH", "TSLL", "TSLP", "TSLQ", "TSLR", "TSLS", "TSLT", "TSLW", "TSLY", "TSLZ", "TSME",
                        "TSMG", "TSMU", "TSMX", "TSMY", "TSMZ", "TSPA", "TSPY", "TSW", "TSYY", "TTAC", "TTAI", "TTEQ",
                        "TUR", "TVAL", "TWEB", "TWM", "TXS", "TXSS", "TXUE", "TXUG", "TYLG", "TZA", "UAPR", "UAUG",
                        "UBOT", "UBRL", "UCC", "UCYB", "UDEC", "UDI", "UDIV", "UEVM", "UFEB", "UFO", "UGE", "UIVM",
                        "UJAN", "UJUL", "UJUN", "ULTY", "ULVM", "UMAR", "UMAY", "UMI", "UMMA", "UNOV", "UOCT", "UPGD",
                        "UPGR", "UPRO", "UPW", "UPWD", "URA", "URAA", "URAX", "URE", "URNJ", "URNM", "USAF", "USAI",
                        "USCA", "USCL", "USD", "USDX", "USE", "USEP", "USMC", "USMF", "USML", "USMV", "USNG", "USNZ",
                        "USOY", "USPX", "USRD", "USRT", "USSE", "USSG", "USVM", "USVT", "USXF", "UTRN", "UTSL", "UVIX",
                        "UWM", "UXI", "UYG", "UYM", "VALQ", "VAMO", "VAW", "VB", "VBK", "VBR", "VCLN", "VCR", "VDC",
                        "VDE", "VDNI", "VEA", "VEGI", "VEGN", "VERS", "VETZ", "VEU", "VFH", "VFLO", "VFMF", "VFMO",
                        "VFMV", "VFQY", "VFVA", "VGK", "VGSR", "VGT", "VHT", "VICE", "VIDI", "VIG", "VIGI", "VIOG",
                        "VIOO", "VIOV", "VIRS", "VIS", "VLLU", "VLU", "VMAT", "VMAX", "VNAM", "VNIE", "VNM", "VNMC",
                        "VNQ", "VNSE", "VO", "VOE", "VOLT", "VONE", "VONG", "VONV", "VOO", "VOOG", "VOOV", "VOT",
                        "VOTE", "VOX", "VPL", "VPU", "VR", "VRAI", "VRTL", "VSDA", "VSGX", "VSLU", "VSMV", "VSS", "VT",
                        "VTEC", "VTEI", "VTHR", "VTI", "VTV", "VTWG", "VTWO", "VTWV", "VUG", "VUSE", "VV", "VWID",
                        "VWO", "VXF", "VXUS", "VYLD", "VYM", "VYMI", "WANT", "WAR", "WBAT", "WBIY", "WCBR", "WCEO",
                        "WCLD", "WCME", "WCMI", "WDTE", "WEBL", "WEBS", "WEED", "WEEL", "WFH", "WGMI", "WINN", "WISE",
                        "WKLY", "WLDR", "WNDY", "WNTR", "WOMN", "WOOD", "WPS", "WRND", "WSML", "WTAI", "WTID", "WTIU",
                        "WTV", "WUCT", "WUGI", "WUSA", "WWJD", "XAIX", "XAPR", "XAR", "XAUG", "XBAP", "XBI", "XBJA",
                        "XBJL", "XBOC", "XBTF", "XBTY", "XC", "XCEM", "XCLR", "XCNY", "XCOR", "XDAP", "XDAT", "XDEC",
                        "XDJA", "XDJL", "XDOC", "XDQQ", "XDSQ", "XDTE", "XES", "XFEB", "XHB", "XHE", "XHS", "XIDV",
                        "XIJN", "XIMR", "XISE", "XJH", "XJR", "XJUL", "XJUN", "XLB", "XLC", "XLE", "XLF", "XLG", "XLI",
                        "XLK", "XLP", "XLRE", "XLU", "XLV", "XLY", "XMAR", "XMAY", "XME", "XMMO", "XMVM", "XNAV",
                        "XNOV", "XNTK", "XOCT", "XOMO", "XOMX", "XOMZ", "XOP", "XOVR", "XPAY", "XPH", "XPND", "XPP",
                        "XRLV", "XRMI", "XRPI", "XRPT", "XRT", "XSD", "XSEP", "XSHD", "XSHQ", "XSVM", "XSW", "XT",
                        "XTAP", "XTJA", "XTJL", "XTL", "XTN", "XTOC", "XTR", "XUDV", "XUSP", "XVOL", "XVV", "XWEB",
                        "XXCH", "XXRP", "XYLG", "XYZG", "XYZY", "YALL", "YANG", "YDEC", "YINN", "YLDE", "YMAG", "YMAR",
                        "YOKE", "YOLO", "YPS", "YQQQ", "YSEP", "YSPY", "YUMY", "ZALT", "ZAP", "ZAPR", "ZAUG", "ZDEK",
                        "ZFEB", "ZHDG", "ZIG", "ZIPP", "ZJAN", "ZJUL", "ZJUN", "ZMAR", "ZMAY", "ZNOV", "ZOCT", "ZSEP",

                        "BRK.B","BRK.A", "TLT", "GLD", "ES", "NQ"


                        ]
