from typing import Any, Self

from ziplime.assets.domain.db.asset import Asset
from ziplime.assets.domain.db.equity_symbol_mapping import EquitySymbolMapping
from ziplime.assets.domain.db.exchange import Exchange


class AssetRepository:

    async def save_assets(self, assets: list[Asset]) -> None: ...

    async def save_exchanges(self, exchanges: list[Exchange]) -> None: ...

    async def save_equity_symbol_mappings(self, equity_symbol_mappings: list[EquitySymbolMapping]) -> None: ...

    async def get_asset_by_sid(self, sid: int) -> Asset: ...

    async def get_asset_by_symbol(self, symbol: str) -> Asset: ...

    def to_json(self): ...

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> Self: ...
